load("@rules_cc//cc:defs.bzl", "cc_library")
cc_library(
    name = "tied_shell_patch",
    hdrs = ["TiedPatchTypes.h", "TiedPatchGeometry.h", "TiedPatchForce.h", "TiedPatchMotion.h", "TiedPatchCoefficients.h"],
    deps = ["//lib_src/math:fixed3_operations"],
    visibility = ["//visibility:public"],
)
cc_library(
    name = "tied_shell_search",
    hdrs = ["TiedSearchTypes.h", "TiedSearchProjection.h", "TiedSearch.h", "TiedSearchBounds.h"],
    deps = [":tied_shell_patch"],
    visibility = ["//visibility:public"],
)
