load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility = ["//visibility:public"])
cc_library(
    name = "reference",
    hdrs = ["Types.h", "Topology.h", "Reference.h"],
    deps = ["//lib_src/elements/solid18:reference"],
)
cc_library(
    name = "force",
    hdrs = ["ForceTypes.h", "ForceChecks.h", "History.h", "Kinematics.h",
            "PointResponse.h", "ForceAssembly.h", "Force.h"],
    deps = [":reference", "//lib_src/elements/solid18:force",
            "//lib_src/materials/law44/solid:point", "//lib_src/materials:solid_caller_values"],
)
