load("//tools/python_demos:defs.bzl", "robodyna_python_demo")

package(default_visibility = ["//visibility:public"])

exports_files(["BUILD.bazel"])

robodyna_python_demo(
    name = "artcar",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_ARTcar.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "city_bus",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_CityBus.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "deformable_soil",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_DeformableSoil.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "feda",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_FEDA.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "gator",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_Gator.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "hmmwv",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_HMMWV.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "hmmwv9_yup",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_HMMWV9_YUP.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "hmmwv_def_soil",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_HMMWV_DefSoil.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "m113",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_M113.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "man_10t",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_MAN_10t.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "rigid_terrain",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_RigidTerrain.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "steering_controller",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_SteeringController.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "suspension_test_rig",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_SuspensionTestRig.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "trailer_json",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_TrailerJSON.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "two_cars",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_TwoCars.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "uazbus",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_UAZBUS.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "wheel_test_rig",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_WheelTestRig.py",
    helpers = ["//src/compatibility/chrono:src/demos/python/SetChronoSolver.py"],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

robodyna_python_demo(
    name = "wheeled_json",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_WheeledJSON.py",
    helpers = [],
    package = "//bindings/python/baseline:package",
    manifest = "//bindings/python/baseline:manifest",
)

filegroup(name = "programs", srcs = [":artcar", ":city_bus", ":deformable_soil", ":feda", ":gator", ":hmmwv", ":hmmwv9_yup", ":hmmwv_def_soil", ":m113", ":man_10t", ":rigid_terrain", ":steering_controller", ":suspension_test_rig", ":trailer_json", ":two_cars", ":uazbus", ":wheel_test_rig", ":wheeled_json"], tags = ["manual", "original-python-demos"])

robodyna_python_demo(
    name = "hmmwv_circle",
    source = "//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_HMMWV_circle.py",
    helpers = [],
    package = "//bindings/python/numpy:package",
    manifest = "//bindings/python/numpy:manifest",
)

robodyna_python_demo(
    name = 'crmterrain_wheeled_vehicle',
    source = '//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_CRMTerrain_WheeledVehicle.py',
    helpers = [],
    package = "//bindings/python/profiles:fsi",
    manifest = "//bindings/python/profiles:fsi_manifest",
)

robodyna_python_demo(
    name = 'wheel_test_rig_crm',
    source = '//src/compatibility/chrono:src/demos/python/vehicle/demo_VEH_WheelTestRig_CRM.py',
    helpers = ['//src/compatibility/chrono:src/demos/python/SetChronoSolver.py'],
    package = "//bindings/python/profiles:fsi",
    manifest = "//bindings/python/profiles:fsi_manifest",
)
