include_guard(GLOBAL)
if(NOT CRASH_TL_FEA_SOURCE_DIR AND ROBO_DYNA_TL_ROOT)
  set(CRASH_TL_FEA_SOURCE_DIR "${ROBO_DYNA_TL_ROOT}")
endif()
if(NOT EXISTS "${CRASH_TL_FEA_SOURCE_DIR}/lib_src/solvers/FENodalStateView.h")
  message(FATAL_ERROR "Accepted surface requires an explicit TL-FEA source root")
endif()
add_library(crash_accepted_surface STATIC "${CMAKE_CURRENT_LIST_DIR}/AcceptedSurfaceMesh.cpp")
target_compile_features(crash_accepted_surface PUBLIC cxx_std_17)
target_include_directories(crash_accepted_surface PUBLIC "${CMAKE_CURRENT_LIST_DIR}" "${CRASH_TL_FEA_SOURCE_DIR}")
target_link_libraries(crash_accepted_surface PUBLIC Chrono::Chrono_core)
