load("//tools/python_demos:defs.bzl", "robodyna_python_demo")

package(default_visibility = ["//visibility:public"])

robodyna_python_demo(
    name = 'cascade',
    source = '//src/compatibility/chrono:src/demos/python/cascade/demo_CAS_cascade.py',
    helpers = [],
    package = "//bindings/python/cascade:package",
    manifest = "//bindings/python/cascade:manifest",
)

robodyna_python_demo(
    name = 'robot',
    source = '//src/compatibility/chrono:src/demos/python/cascade/demo_CAS_robot.py',
    helpers = [],
    package = "//bindings/python/cascade:package",
    manifest = "//bindings/python/cascade:manifest",
)

robodyna_python_demo(
    name = 'stepfile',
    source = '//src/compatibility/chrono:src/demos/python/cascade/demo_CAS_stepfile.py',
    helpers = [],
    package = "//bindings/python/cascade:package",
    manifest = "//bindings/python/cascade:manifest",
)
