# Install-time adapter only. foreign_cc stages source/header/data inputs as
# symlinks, but an installed tree must survive removal of those staging paths.
# Built libraries are deliberately outside this pass: they come from this build.
function(robodyna_materialize_installed_sources directory output_records)
  if(NOT IS_DIRECTORY "${directory}")
    message(FATAL_ERROR "Expected installed DEME source/data directory: ${directory}")
  endif()
  file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE "${directory}/*")
  set(records "[]")
  set(count 0)
  foreach(path IN LISTS entries)
    if(IS_SYMLINK "${path}")
      if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Unresolved or directory DEME install symlink: ${path}")
      endif()
      file(SHA256 "${path}" source_sha)
      set(temporary "${path}.robodyna-copy")
      if(EXISTS "${temporary}" OR IS_SYMLINK "${temporary}")
        message(FATAL_ERROR "Unexpected temporary DEME install output: ${temporary}")
      endif()
      configure_file("${path}" "${temporary}" COPYONLY)
      file(SHA256 "${temporary}" copy_sha)
      if(IS_SYMLINK "${temporary}" OR NOT source_sha STREQUAL copy_sha)
        message(FATAL_ERROR "DEME install materialization changed source bytes: ${path}")
      endif()
      file(REMOVE "${path}")
      file(RENAME "${temporary}" "${path}")
      file(RELATIVE_PATH relative "${directory}" "${path}")
      # These are generated source/data names, not untrusted command text.
      string(REPLACE "\\" "\\\\" relative "${relative}")
      string(REPLACE "\"" "\\\"" relative "${relative}")
      string(JSON record SET "{}" path "\"${relative}\"")
      string(JSON record SET "${record}" source_sha256 "\"${source_sha}\"")
      string(JSON record SET "${record}" installed_sha256 "\"${copy_sha}\"")
      string(JSON records SET "${records}" ${count} "${record}")
      math(EXPR count "${count} + 1")
    endif()
  endforeach()
  set(${output_records} "${records}" PARENT_SCOPE)
endfunction()

if(NOT DEFINED ROBODYNA_DEME_INSTALL_INCLUDE_DIR OR
   NOT DEFINED ROBODYNA_DEME_INSTALL_DATA_DIR OR
   NOT DEFINED ROBODYNA_DEME_JITIFY_SHA256)
  message(FATAL_ERROR "DEME install roots must come from the owning CMake adapter")
endif()
set(include_root "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/${ROBODYNA_DEME_INSTALL_INCLUDE_DIR}")
set(data_root "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/${ROBODYNA_DEME_INSTALL_DATA_DIR}/DEME")
robodyna_materialize_installed_sources("${include_root}" include_records)
robodyna_materialize_installed_sources("${data_root}" data_records)
file(SHA256 "${include_root}/jitify/jitify.hpp" jitify_sha)
if(NOT jitify_sha STREQUAL ROBODYNA_DEME_JITIFY_SHA256)
  message(FATAL_ERROR "Installed Jitify header differs from the admitted SDK bytes")
endif()
string(JSON include_count LENGTH "${include_records}")
string(JSON data_count LENGTH "${data_records}")
math(EXPR count "${include_count} + ${data_count}")
string(JSON receipt SET "{}" schema "\"robodyna.deme_installed_sources.v1\"")
string(JSON receipt SET "${receipt}" materialized_symlinks ${count})
string(JSON receipt SET "${receipt}" headers "${include_records}")
string(JSON receipt SET "${receipt}" runtime_data "${data_records}")
string(JSON receipt SET "${receipt}" jitify_sha256 "\"${jitify_sha}\"")
file(WRITE "${data_root}/robodyna-installed-sources.json" "${receipt}\n")
message(STATUS "Materialized ${count} DEME header/runtime-data symlinks; hashes recorded")
