enable_language(Fortran)
set(TL_TAB1_GLASS_NATIVE ON CACHE BOOL "" FORCE)
set(TL_TAB1_GLASS_CUDA OFF CACHE BOOL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../shell_tab1_glass" glass-section)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(placement_source "${CMAKE_CURRENT_SOURCE_DIR}/native")
set(placement_prepared "${CMAKE_CURRENT_BINARY_DIR}/placement-prepared")
execute_process(COMMAND "${Python3_EXECUTABLE}" -B "${placement_source}/prepare_sources.py"
  --output "${placement_prepared}" RESULT_VARIABLE status ERROR_VARIABLE diagnostic)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Native placement source preparation failed: ${diagnostic}")
endif()
add_custom_target(shell_reference_placement_sources
  COMMAND "${Python3_EXECUTABLE}" -B "${placement_source}/prepare_sources.py"
    --output "${placement_prepared}" --check VERBATIM)
add_library(shell_reference_placement_native STATIC native/NativePlacement.F native/NativeCaller.F90
  "${placement_prepared}/PlacementWm.F90" "${placement_prepared}/PlacementPacket.F90")
add_dependencies(shell_reference_placement_native shell_reference_placement_sources)
foreach(property INCLUDE_DIRECTORIES COMPILE_DEFINITIONS COMPILE_OPTIONS)
  get_target_property(value shell_layered_failure_native ${property})
  set_property(TARGET shell_reference_placement_native PROPERTY ${property} "${value}")
endforeach()
get_target_property(placement_glass_modules shell_tab1_glass_native Fortran_MODULE_DIRECTORY)
get_target_property(placement_failure_modules shell_layered_failure_native Fortran_MODULE_DIRECTORY)
set(placement_modules "${CMAKE_CURRENT_BINARY_DIR}/placement-modules")
file(MAKE_DIRECTORY "${placement_modules}")
set_target_properties(shell_reference_placement_native PROPERTIES Fortran_MODULE_DIRECTORY "${placement_modules}")
target_include_directories(shell_reference_placement_native BEFORE PRIVATE "${placement_prepared}"
  "${placement_glass_modules}" "${placement_failure_modules}" "${placement_modules}")
target_link_libraries(shell_reference_placement_native PUBLIC shell_tab1_glass_native)
add_library(placement_native_test_support STATIC PlacementNativeSupport.cpp)
target_include_directories(placement_native_test_support PUBLIC "${TL_ROOT}")
target_compile_features(placement_native_test_support PUBLIC cxx_std_17)
target_compile_options(placement_native_test_support PRIVATE -fno-fast-math -ffp-contract=off)
target_link_libraries(placement_native_test_support PUBLIC
  shell_reference_placement_native shell_tab1_glass_test_support GTest::gtest_main)
add_executable(shell_reference_placement_native_check PlacementNativeTest.cpp)
target_compile_options(shell_reference_placement_native_check PRIVATE -fno-fast-math -ffp-contract=off)
target_link_libraries(shell_reference_placement_native_check PRIVATE placement_native_test_support)
add_test(NAME shell_reference_placement_native COMMAND shell_reference_placement_native_check)
