load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "brand_video",
    srcs = ["brand_video.py"],
    main = "brand_video.py",
    deps = ["//src/compatibility/app:python_video"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "export_video",
    srcs = ["export_video.py"],
    main = "export_video.py",
    deps = ["//src/compatibility/app:python_video"],
    visibility = ["//visibility:public"],
)
