"""Explicit retained CMake source groups for the admitted Vehicle profile.

No optional implementation is selected by globbing. Source ownership tests compare
these lists with the original module declarations and the shared SCM/STB owners.
"""

VEHICLE_GROUPS = {'base': {'cmake_group': 'CV_BASE_FILES',
          'sources': ['src/chrono_vehicle/ChChassis.cpp',
                      'src/chrono_vehicle/ChDriver.cpp',
                      'src/chrono_vehicle/ChPart.cpp',
                      'src/chrono_vehicle/ChDriveline.cpp',
                      'src/chrono_vehicle/ChPowertrainAssembly.cpp',
                      'src/chrono_vehicle/ChEngine.cpp',
                      'src/chrono_vehicle/ChTransmission.cpp',
                      'src/chrono_vehicle/ChSubsysDefs.cpp',
                      'src/chrono_vehicle/ChVehicle.cpp',
                      'src/chrono_vehicle/ChVehicleVisualSystem.cpp'],
          'headers': ['src/chrono_vehicle/ChChassis.h',
                      'src/chrono_vehicle/ChDriver.h',
                      'src/chrono_vehicle/ChPart.h',
                      'src/chrono_vehicle/ChDriveline.h',
                      'src/chrono_vehicle/ChPowertrainAssembly.h',
                      'src/chrono_vehicle/ChEngine.h',
                      'src/chrono_vehicle/ChTransmission.h',
                      'src/chrono_vehicle/ChVehicle.h',
                      'src/chrono_vehicle/ChVehicleOutput.h',
                      'src/chrono_vehicle/ChVehicleVisualSystem.h']},
 'chassis': {'cmake_group': 'CV_CHASSIS_FILES',
             'sources': ['src/chrono_vehicle/chassis/ChRigidChassis.cpp',
                         'src/chrono_vehicle/chassis/ChChassisConnectorArticulated.cpp',
                         'src/chrono_vehicle/chassis/ChChassisConnectorHitch.cpp',
                         'src/chrono_vehicle/chassis/ChChassisConnectorFifthWheel.cpp',
                         'src/chrono_vehicle/chassis/ChChassisConnectorTorsion.cpp',
                         'src/chrono_vehicle/chassis/RigidChassis.cpp',
                         'src/chrono_vehicle/chassis/ChassisConnectorHitch.cpp',
                         'src/chrono_vehicle/chassis/ChassisConnectorFifthWheel.cpp',
                         'src/chrono_vehicle/chassis/ChassisConnectorArticulated.cpp',
                         'src/chrono_vehicle/chassis/ChassisConnectorTorsion.cpp'],
             'headers': ['src/chrono_vehicle/chassis/ChRigidChassis.h',
                         'src/chrono_vehicle/chassis/ChChassisConnectorArticulated.h',
                         'src/chrono_vehicle/chassis/ChChassisConnectorHitch.h',
                         'src/chrono_vehicle/chassis/ChChassisConnectorFifthWheel.h',
                         'src/chrono_vehicle/chassis/ChChassisConnectorTorsion.h',
                         'src/chrono_vehicle/chassis/RigidChassis.h',
                         'src/chrono_vehicle/chassis/ChassisConnectorHitch.h',
                         'src/chrono_vehicle/chassis/ChassisConnectorFifthWheel.h',
                         'src/chrono_vehicle/chassis/ChassisConnectorArticulated.h',
                         'src/chrono_vehicle/chassis/ChassisConnectorTorsion.h']},
 'driver': {'cmake_group': 'CV_DRIVER_FILES',
            'sources': ['src/chrono_vehicle/driver/ChDataDriver.cpp',
                        'src/chrono_vehicle/driver/ChHumanDriver.cpp',
                        'src/chrono_vehicle/driver/ChAIDriver.cpp',
                        'src/chrono_vehicle/driver/ChPathFollowerDriver.cpp',
                        'src/chrono_vehicle/driver/ChPathFollowerACCDriver.cpp',
                        'src/chrono_vehicle/driver/ChInteractiveDriver.cpp',
                        'src/chrono_vehicle/driver/AIDriver.cpp'],
            'headers': ['src/chrono_vehicle/driver/ChDataDriver.h',
                        'src/chrono_vehicle/driver/ChHumanDriver.h',
                        'src/chrono_vehicle/driver/ChAIDriver.h',
                        'src/chrono_vehicle/driver/ChPathFollowerDriver.h',
                        'src/chrono_vehicle/driver/ChPathFollowerACCDriver.h',
                        'src/chrono_vehicle/driver/ChInteractiveDriver.h',
                        'src/chrono_vehicle/driver/AIDriver.h']},
 'powertrain': {'cmake_group': 'CV_POVERTRAIN_FILES',
                'sources': ['src/chrono_vehicle/powertrain/ChEngineSimple.cpp',
                            'src/chrono_vehicle/powertrain/ChEngineSimpleMap.cpp',
                            'src/chrono_vehicle/powertrain/ChEngineShafts.cpp',
                            'src/chrono_vehicle/powertrain/EngineSimple.cpp',
                            'src/chrono_vehicle/powertrain/EngineSimpleMap.cpp',
                            'src/chrono_vehicle/powertrain/EngineShafts.cpp',
                            'src/chrono_vehicle/powertrain/ChAutomaticTransmissionSimpleMap.cpp',
                            'src/chrono_vehicle/powertrain/ChAutomaticTransmissionShafts.cpp',
                            'src/chrono_vehicle/powertrain/ChManualTransmissionShafts.cpp',
                            'src/chrono_vehicle/powertrain/AutomaticTransmissionSimpleMap.cpp',
                            'src/chrono_vehicle/powertrain/AutomaticTransmissionShafts.cpp',
                            'src/chrono_vehicle/powertrain/ManualTransmissionShafts.cpp',
                            'src/chrono_vehicle/powertrain/ChAutomaticTransmissionSimpleCVT.cpp',
                            'src/chrono_vehicle/powertrain/AutomaticTransmissionSimpleCVT.cpp'],
                'headers': ['src/chrono_vehicle/powertrain/ChEngineSimple.h',
                            'src/chrono_vehicle/powertrain/ChEngineSimpleMap.h',
                            'src/chrono_vehicle/powertrain/ChEngineShafts.h',
                            'src/chrono_vehicle/powertrain/EngineSimple.h',
                            'src/chrono_vehicle/powertrain/EngineSimpleMap.h',
                            'src/chrono_vehicle/powertrain/EngineShafts.h',
                            'src/chrono_vehicle/powertrain/ChAutomaticTransmissionSimpleMap.h',
                            'src/chrono_vehicle/powertrain/ChAutomaticTransmissionShafts.h',
                            'src/chrono_vehicle/powertrain/ChManualTransmissionShafts.h',
                            'src/chrono_vehicle/powertrain/AutomaticTransmissionSimpleMap.h',
                            'src/chrono_vehicle/powertrain/AutomaticTransmissionShafts.h',
                            'src/chrono_vehicle/powertrain/ManualTransmissionShafts.h',
                            'src/chrono_vehicle/powertrain/ChAutomaticTransmissionSimpleCVT.h',
                            'src/chrono_vehicle/powertrain/AutomaticTransmissionSimpleCVT.h']},
 'terrain': {'cmake_group': 'CV_TERRAIN_FILES',
             'sources': ['src/chrono_vehicle/terrain/FlatTerrain.cpp',
                         'src/chrono_vehicle/terrain/ObsModTerrain.cpp',
                         'src/chrono_vehicle/terrain/RigidTerrain.cpp',
                         'src/chrono_vehicle/terrain/RandomSurfaceTerrain.cpp',
                         'src/chrono_vehicle/terrain/GranularTerrain.cpp',
                         'src/chrono_vehicle/terrain/FEATerrain.cpp'],
             'headers': ['src/chrono_vehicle/terrain/FlatTerrain.h',
                         'src/chrono_vehicle/terrain/ObsModTerrain.h',
                         'src/chrono_vehicle/terrain/RigidTerrain.h',
                         'src/chrono_vehicle/terrain/RandomSurfaceTerrain.h',
                         'src/chrono_vehicle/terrain/GranularTerrain.h',
                         'src/chrono_vehicle/terrain/FEATerrain.h']},
 'utils': {'cmake_group': 'CV_UTILS_FILES',
           'sources': ['src/chrono_vehicle/utils/ChSteeringController.cpp',
                       'src/chrono_vehicle/utils/ChSpeedController.cpp',
                       'src/chrono_vehicle/utils/ChAdaptiveSpeedController.cpp',
                       'src/chrono_vehicle/utils/ChVehiclePath.cpp',
                       'src/chrono_vehicle/utils/ChVehicleUtilsJSON.cpp'],
           'headers': ['src/chrono_vehicle/utils/ChSteeringController.h',
                       'src/chrono_vehicle/utils/ChSpeedController.h',
                       'src/chrono_vehicle/utils/ChAdaptiveSpeedController.h',
                       'src/chrono_vehicle/utils/ChVehiclePath.h',
                       'src/chrono_vehicle/utils/ChVehicleUtilsJSON.h']},
 'wheeled_base': {'cmake_group': 'CV_WV_BASE_FILES',
                  'sources': ['src/chrono_vehicle/wheeled_vehicle/ChAxle.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChAntirollBar.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChBrake.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChDrivelineWV.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChSuspension.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChSteering.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChSubchassis.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChWheeledTrailer.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChWheeledVehicle.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChSpindle.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChWheel.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/ChTire.cpp'],
                  'headers': ['src/chrono_vehicle/wheeled_vehicle/ChAxle.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChAntirollBar.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChBrake.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChDrivelineWV.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChSuspension.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChSteering.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChSubchassis.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChWheeledTrailer.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChWheeledVehicle.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChSpindle.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChWheel.h',
                              'src/chrono_vehicle/wheeled_vehicle/ChTire.h']},
 'wheeled_antiroll': {'cmake_group': 'CV_WV_ANTIROLL_FILES',
                      'sources': ['src/chrono_vehicle/wheeled_vehicle/antirollbar/ChAntirollBarRSD.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/antirollbar/AntirollBarRSD.cpp'],
                      'headers': ['src/chrono_vehicle/wheeled_vehicle/antirollbar/ChAntirollBarRSD.h',
                                  'src/chrono_vehicle/wheeled_vehicle/antirollbar/AntirollBarRSD.h']},
 'wheeled_brake': {'cmake_group': 'CV_WV_BRAKE_FILES',
                   'sources': ['src/chrono_vehicle/wheeled_vehicle/brake/ChBrakeSimple.cpp',
                               'src/chrono_vehicle/wheeled_vehicle/brake/ChBrakeShafts.cpp',
                               'src/chrono_vehicle/wheeled_vehicle/brake/BrakeSimple.cpp',
                               'src/chrono_vehicle/wheeled_vehicle/brake/BrakeShafts.cpp'],
                   'headers': ['src/chrono_vehicle/wheeled_vehicle/brake/ChBrakeSimple.h',
                               'src/chrono_vehicle/wheeled_vehicle/brake/ChBrakeShafts.h',
                               'src/chrono_vehicle/wheeled_vehicle/brake/BrakeSimple.h',
                               'src/chrono_vehicle/wheeled_vehicle/brake/BrakeShafts.h']},
 'wheeled_driveline': {'cmake_group': 'CV_WV_DRIVELINE_FILES',
                       'sources': ['src/chrono_vehicle/wheeled_vehicle/driveline/ChShaftsDriveline2WD.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChShaftsDriveline4WD.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChShaftsDriveline6WD.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChShaftsDriveline8WD.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChSimpleDrivelineXWD.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChSimpleDriveline.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ShaftsDriveline2WD.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ShaftsDriveline4WD.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/SimpleDriveline.cpp',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/SimpleDrivelineXWD.cpp'],
                       'headers': ['src/chrono_vehicle/wheeled_vehicle/driveline/ChShaftsDriveline2WD.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChShaftsDriveline4WD.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChShaftsDriveline6WD.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChShaftsDriveline8WD.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChSimpleDrivelineXWD.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ChSimpleDriveline.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ShaftsDriveline2WD.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/ShaftsDriveline4WD.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/SimpleDriveline.h',
                                   'src/chrono_vehicle/wheeled_vehicle/driveline/SimpleDrivelineXWD.h']},
 'wheeled_steering': {'cmake_group': 'CV_WV_STEERING_FILES',
                      'sources': ['src/chrono_vehicle/wheeled_vehicle/steering/ChPitmanArm.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/ChPitmanArmShafts.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/ChRackPinion.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/ChRotaryArm.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/PitmanArm.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/RackPinion.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/RotaryArm.cpp'],
                      'headers': ['src/chrono_vehicle/wheeled_vehicle/steering/ChPitmanArm.h',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/ChPitmanArmShafts.h',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/ChRackPinion.h',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/ChRotaryArm.h',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/PitmanArm.h',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/RackPinion.h',
                                  'src/chrono_vehicle/wheeled_vehicle/steering/RotaryArm.h']},
 'wheeled_subchassis': {'cmake_group': 'CV_WV_SUBCHASSIS_FILES',
                        'sources': ['src/chrono_vehicle/wheeled_vehicle/subchassis/ChBalancer.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/subchassis/Balancer.cpp'],
                        'headers': ['src/chrono_vehicle/wheeled_vehicle/subchassis/ChBalancer.h',
                                    'src/chrono_vehicle/wheeled_vehicle/subchassis/Balancer.h']},
 'wheeled_suspension': {'cmake_group': 'CV_WV_SUSPENSION_FILES',
                        'sources': ['src/chrono_vehicle/wheeled_vehicle/suspension/ChDeDionAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChDoubleWishbone.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChDoubleWishboneReduced.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSingleWishbone.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSolidAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChMultiLink.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChHendricksonPRIMAXX.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChMacPhersonStrut.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSemiTrailingArm.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChThreeLinkIRS.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChRigidSuspension.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChRigidPinnedAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChLeafspringAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChPushPipeAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSAELeafspringAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSolidBellcrankThreeLinkAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSolidThreeLinkAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChToeBarDeDionAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChToeBarLeafspringAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSAEToeBarLeafspringAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChToeBarPushPipeAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChGenericWheeledSuspension.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChRigidPanhardAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChToeBarRigidPanhardAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/DeDionAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/DoubleWishbone.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/DoubleWishboneReduced.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SingleWishbone.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SolidAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/MultiLink.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/HendricksonPRIMAXX.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/MacPhersonStrut.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SemiTrailingArm.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ThreeLinkIRS.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/RigidSuspension.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/RigidPinnedAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/LeafspringAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/PushPipeAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SAELeafspringAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SolidBellcrankThreeLinkAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SolidThreeLinkAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ToeBarDeDionAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ToeBarLeafspringAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SAEToeBarLeafspringAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ToeBarPushPipeAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/GenericWheeledSuspension.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/RigidPanhardAxle.cpp',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ToeBarRigidPanhardAxle.cpp'],
                        'headers': ['src/chrono_vehicle/wheeled_vehicle/suspension/ChDeDionAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChDoubleWishbone.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChDoubleWishboneReduced.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSingleWishbone.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSolidAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChMultiLink.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChHendricksonPRIMAXX.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChMacPhersonStrut.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSemiTrailingArm.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChThreeLinkIRS.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChRigidSuspension.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChRigidPinnedAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChLeafspringAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChPushPipeAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSAELeafspringAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSolidBellcrankThreeLinkAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSolidThreeLinkAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChToeBarDeDionAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChToeBarLeafspringAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChSAEToeBarLeafspringAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChToeBarPushPipeAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChGenericWheeledSuspension.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChRigidPanhardAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ChToeBarRigidPanhardAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/DeDionAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/DoubleWishbone.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/DoubleWishboneReduced.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SingleWishbone.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SolidAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/MultiLink.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/HendricksonPRIMAXX.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/MacPhersonStrut.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SemiTrailingArm.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ThreeLinkIRS.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/RigidSuspension.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/RigidPinnedAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/LeafspringAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/PushPipeAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SAELeafspringAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SolidBellcrankThreeLinkAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SolidThreeLinkAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ToeBarDeDionAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ToeBarLeafspringAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/SAEToeBarLeafspringAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ToeBarPushPipeAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/GenericWheeledSuspension.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/RigidPanhardAxle.h',
                                    'src/chrono_vehicle/wheeled_vehicle/suspension/ToeBarRigidPanhardAxle.h']},
 'wheeled_test_rig': {'cmake_group': 'CV_WV_TEST_RIG_FILES',
                      'sources': ['src/chrono_vehicle/wheeled_vehicle/test_rig/ChSuspensionTestRig.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/test_rig/ChSuspensionTestRigDriver.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/test_rig/ChSuspensionTestRigDataDriver.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/test_rig/ChSuspensionTestRigInteractiveDriver.cpp',
                                  'src/chrono_vehicle/wheeled_vehicle/test_rig/ChWheelTestRig.cpp'],
                      'headers': ['src/chrono_vehicle/wheeled_vehicle/test_rig/ChSuspensionTestRig.h',
                                  'src/chrono_vehicle/wheeled_vehicle/test_rig/ChSuspensionTestRigDriver.h',
                                  'src/chrono_vehicle/wheeled_vehicle/test_rig/ChSuspensionTestRigDataDriver.h',
                                  'src/chrono_vehicle/wheeled_vehicle/test_rig/ChSuspensionTestRigInteractiveDriver.h',
                                  'src/chrono_vehicle/wheeled_vehicle/test_rig/ChWheelTestRig.h']},
 'wheeled_tire': {'cmake_group': 'CV_WV_TIRE_FILES',
                  'sources': ['src/chrono_vehicle/wheeled_vehicle/tire/ChRigidTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChForceElementTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChPac89Tire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChFialaTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChTMsimpleTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChTMeasyTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChPac02Tire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/RigidTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/Pac89Tire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/FialaTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/TMeasyTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/TMsimpleTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/Pac02Tire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChDeformableTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChANCFTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChReissnerTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChFEATire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ReissnerTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ANCFTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/FEATire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ANCFToroidalTire.cpp',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ReissnerToroidalTire.cpp'],
                  'headers': ['src/chrono_vehicle/wheeled_vehicle/tire/ChRigidTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChForceElementTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChPac89Tire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChFialaTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChTMsimpleTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChTMeasyTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChPac02Tire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/RigidTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/Pac89Tire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/FialaTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/TMeasyTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/TMsimpleTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/Pac02Tire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChDeformableTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChANCFTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChReissnerTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ChFEATire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ReissnerTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ANCFTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/FEATire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ANCFToroidalTire.h',
                              'src/chrono_vehicle/wheeled_vehicle/tire/ReissnerToroidalTire.h']},
 'wheeled_vehicle': {'cmake_group': 'CV_WV_VEHICLE_FILES',
                     'sources': ['src/chrono_vehicle/wheeled_vehicle/vehicle/WheeledTrailer.cpp',
                                 'src/chrono_vehicle/wheeled_vehicle/vehicle/WheeledVehicle.cpp'],
                     'headers': ['src/chrono_vehicle/wheeled_vehicle/vehicle/WheeledTrailer.h',
                                 'src/chrono_vehicle/wheeled_vehicle/vehicle/WheeledVehicle.h']},
 'wheeled_wheel': {'cmake_group': 'CV_WV_WHEEL_FILES',
                   'sources': ['src/chrono_vehicle/wheeled_vehicle/wheel/Wheel.cpp'],
                   'headers': ['src/chrono_vehicle/wheeled_vehicle/wheel/Wheel.h']},
 'tracked_base': {'cmake_group': 'CV_TV_BASE_FILES',
                  'sources': ['src/chrono_vehicle/tracked_vehicle/ChIdler.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackWheel.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackSuspension.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChSprocket.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackAssembly.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackBrake.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChDrivelineTV.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackedVehicle.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackShoe.cpp',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackContactManager.cpp'],
                  'headers': ['src/chrono_vehicle/tracked_vehicle/ChIdler.h',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackWheel.h',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackSuspension.h',
                              'src/chrono_vehicle/tracked_vehicle/ChSprocket.h',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackAssembly.h',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackBrake.h',
                              'src/chrono_vehicle/tracked_vehicle/ChDrivelineTV.h',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackedVehicle.h',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackShoe.h',
                              'src/chrono_vehicle/tracked_vehicle/ChTrackContactManager.h']},
 'tracked_brake': {'cmake_group': 'CV_TV_BRAKE_FILES',
                   'sources': ['src/chrono_vehicle/tracked_vehicle/brake/ChTrackBrakeSimple.cpp',
                               'src/chrono_vehicle/tracked_vehicle/brake/ChTrackBrakeShafts.cpp',
                               'src/chrono_vehicle/tracked_vehicle/brake/TrackBrakeSimple.cpp',
                               'src/chrono_vehicle/tracked_vehicle/brake/TrackBrakeShafts.cpp'],
                   'headers': ['src/chrono_vehicle/tracked_vehicle/brake/ChTrackBrakeSimple.h',
                               'src/chrono_vehicle/tracked_vehicle/brake/ChTrackBrakeShafts.h',
                               'src/chrono_vehicle/tracked_vehicle/brake/TrackBrakeSimple.h',
                               'src/chrono_vehicle/tracked_vehicle/brake/TrackBrakeShafts.h']},
 'tracked_driveline': {'cmake_group': 'CV_TV_DRIVELINE_FILES',
                       'sources': ['src/chrono_vehicle/tracked_vehicle/driveline/ChTrackDrivelineBDS.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/driveline/ChSimpleTrackDriveline.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/driveline/TrackDrivelineBDS.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/driveline/SimpleTrackDriveline.cpp'],
                       'headers': ['src/chrono_vehicle/tracked_vehicle/driveline/ChTrackDrivelineBDS.h',
                                   'src/chrono_vehicle/tracked_vehicle/driveline/ChSimpleTrackDriveline.h',
                                   'src/chrono_vehicle/tracked_vehicle/driveline/TrackDrivelineBDS.h',
                                   'src/chrono_vehicle/tracked_vehicle/driveline/SimpleTrackDriveline.h']},
 'tracked_idler': {'cmake_group': 'CV_TV_IDLER_FILES',
                   'sources': ['src/chrono_vehicle/tracked_vehicle/idler/ChTranslationalIdler.cpp',
                               'src/chrono_vehicle/tracked_vehicle/idler/ChDistanceIdler.cpp',
                               'src/chrono_vehicle/tracked_vehicle/idler/TranslationalIdler.cpp',
                               'src/chrono_vehicle/tracked_vehicle/idler/DistanceIdler.cpp'],
                   'headers': ['src/chrono_vehicle/tracked_vehicle/idler/ChTranslationalIdler.h',
                               'src/chrono_vehicle/tracked_vehicle/idler/ChDistanceIdler.h',
                               'src/chrono_vehicle/tracked_vehicle/idler/TranslationalIdler.h',
                               'src/chrono_vehicle/tracked_vehicle/idler/DistanceIdler.h']},
 'tracked_trackwheel': {'cmake_group': 'CV_TV_TRACKWHEEL_FILES',
                        'sources': ['src/chrono_vehicle/tracked_vehicle/track_wheel/ChSingleTrackWheel.cpp',
                                    'src/chrono_vehicle/tracked_vehicle/track_wheel/ChDoubleTrackWheel.cpp',
                                    'src/chrono_vehicle/tracked_vehicle/track_wheel/SingleTrackWheel.cpp',
                                    'src/chrono_vehicle/tracked_vehicle/track_wheel/DoubleTrackWheel.cpp'],
                        'headers': ['src/chrono_vehicle/tracked_vehicle/track_wheel/ChSingleTrackWheel.h',
                                    'src/chrono_vehicle/tracked_vehicle/track_wheel/ChDoubleTrackWheel.h',
                                    'src/chrono_vehicle/tracked_vehicle/track_wheel/SingleTrackWheel.h',
                                    'src/chrono_vehicle/tracked_vehicle/track_wheel/DoubleTrackWheel.h']},
 'tracked_sprocket': {'cmake_group': 'CV_TV_SPROCKET_FILES',
                      'sources': ['src/chrono_vehicle/tracked_vehicle/sprocket/ChSprocketSinglePin.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/ChSprocketDoublePin.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/ChSprocketBand.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/SprocketSinglePin.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/SprocketDoublePin.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/SprocketBand.cpp'],
                      'headers': ['src/chrono_vehicle/tracked_vehicle/sprocket/ChSprocketSinglePin.h',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/ChSprocketDoublePin.h',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/ChSprocketBand.h',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/SprocketSinglePin.h',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/SprocketDoublePin.h',
                                  'src/chrono_vehicle/tracked_vehicle/sprocket/SprocketBand.h']},
 'tracked_suspension': {'cmake_group': 'CV_TV_SUSPENSION_FILES',
                        'sources': ['src/chrono_vehicle/tracked_vehicle/suspension/ChTranslationalDamperSuspension.cpp',
                                    'src/chrono_vehicle/tracked_vehicle/suspension/ChRotationalDamperSuspension.cpp',
                                    'src/chrono_vehicle/tracked_vehicle/suspension/TranslationalDamperSuspension.cpp',
                                    'src/chrono_vehicle/tracked_vehicle/suspension/RotationalDamperSuspension.cpp'],
                        'headers': ['src/chrono_vehicle/tracked_vehicle/suspension/ChTranslationalDamperSuspension.h',
                                    'src/chrono_vehicle/tracked_vehicle/suspension/ChRotationalDamperSuspension.h',
                                    'src/chrono_vehicle/tracked_vehicle/suspension/TranslationalDamperSuspension.h',
                                    'src/chrono_vehicle/tracked_vehicle/suspension/RotationalDamperSuspension.h']},
 'tracked_trackshoe': {'cmake_group': 'CV_TV_TRACKSHOE_FILES',
                       'sources': ['src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeSegmented.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeSinglePin.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeDoublePin.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeBand.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeBandBushing.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/TrackShoeSinglePin.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/TrackShoeDoublePin.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/TrackShoeBandBushing.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeBandANCF.cpp',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/TrackShoeBandANCF.cpp'],
                       'headers': ['src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeSegmented.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeSinglePin.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeDoublePin.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeBand.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeBandBushing.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/TrackShoeSinglePin.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/TrackShoeDoublePin.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/TrackShoeBandBushing.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/ChTrackShoeBandANCF.h',
                                   'src/chrono_vehicle/tracked_vehicle/track_shoe/TrackShoeBandANCF.h']},
 'tracked_trackassembly': {'cmake_group': 'CV_TV_TRACKASSEMBLY_FILES',
                           'sources': ['src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblySegmented.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblySinglePin.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblyDoublePin.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblyBand.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblyBandBushing.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/TrackAssemblySinglePin.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/TrackAssemblyDoublePin.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/TrackAssemblyBandBushing.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblyBandANCF.cpp',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/TrackAssemblyBandANCF.cpp'],
                           'headers': ['src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblySegmented.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblySinglePin.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblyDoublePin.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblyBand.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblyBandBushing.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/TrackAssemblySinglePin.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/TrackAssemblyDoublePin.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/TrackAssemblyBandBushing.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/ChTrackAssemblyBandANCF.h',
                                       'src/chrono_vehicle/tracked_vehicle/track_assembly/TrackAssemblyBandANCF.h']},
 'tracked_test_rig': {'cmake_group': 'CV_TV_TEST_RIG_FILES',
                      'sources': ['src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRig.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRigDriver.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRigDataDriver.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRigRoadDriver.cpp',
                                  'src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRigInteractiveDriver.cpp'],
                      'headers': ['src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRig.h',
                                  'src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRigDriver.h',
                                  'src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRigDataDriver.h',
                                  'src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRigRoadDriver.h',
                                  'src/chrono_vehicle/tracked_vehicle/test_rig/ChTrackTestRigInteractiveDriver.h']},
 'tracked_utils': {'cmake_group': 'CV_TV_UTILS_FILES', 'sources': [], 'headers': []},
 'tracked_vehicle': {'cmake_group': 'CV_TV_VEHICLE_FILES',
                     'sources': ['src/chrono_vehicle/tracked_vehicle/vehicle/TrackedVehicle.cpp'],
                     'headers': ['src/chrono_vehicle/tracked_vehicle/vehicle/TrackedVehicle.h']}}
