include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/RadiossType25Friction.cmake")
add_library(tl_radioss_type25_assembly INTERFACE)
target_link_libraries(tl_radioss_type25_assembly INTERFACE tl_radioss_type25_friction)
