include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/RadiossType25Normal.cmake")
set(_type25_search "${CMAKE_CURRENT_LIST_DIR}/radioss_type25/search")
add_library(tl_radioss_type25_search_values STATIC "${_type25_search}/Layout.cpp" "${_type25_search}/Preflight.cpp")
target_link_libraries(tl_radioss_type25_search_values PUBLIC tl_radioss_type25_normal)
target_compile_options(tl_radioss_type25_search_values PUBLIC
  "$<$<COMPILE_LANGUAGE:CXX>:-fno-fast-math;-ffp-contract=off>"
  "$<$<COMPILE_LANG_AND_ID:CUDA,NVIDIA>:--fmad=false;--prec-div=true;--prec-sqrt=true;--ftz=false;-Xcompiler=-fno-fast-math,-ffp-contract=off>")
option(TYPE25_SEARCH_CUDA "Build bounded native search maintenance on CUDA" OFF)
if(TYPE25_SEARCH_CUDA)
  find_package(CUDAToolkit REQUIRED)
  get_property(_languages GLOBAL PROPERTY ENABLED_LANGUAGES)
  if(NOT "CUDA" IN_LIST _languages)
    enable_language(CUDA)
  endif()
  add_library(tl_radioss_type25_search STATIC "${_type25_search}/Initialize.cpp" "${_type25_search}/Maintenance.cpp" "${_type25_search}/Checks.cpp" "${_type25_search}/Kernels.cu")
  target_link_libraries(tl_radioss_type25_search PUBLIC tl_radioss_type25_search_values CUDA::cudart)
  set_target_properties(tl_radioss_type25_search PROPERTIES CUDA_STANDARD 17 CUDA_STANDARD_REQUIRED YES)
endif()
