"""Explicit N1 include compatibility inventory; legacy names are intentional."""

HEADER_PAIRS = [
    ("robodyna/core/RbVector3.h", "chrono/core/ChVector3.h"),
    ("robodyna/core/RbQuaternion.h", "chrono/core/ChQuaternion.h"),
    ("robodyna/core/RbFrame.h", "chrono/core/ChFrame.h"),
    ("robodyna/core/RbMatrix33.h", "chrono/core/ChMatrix33.h"),
    ("robodyna/core/RbTypes.h", "chrono/core/ChTypes.h"),
    ("robodyna/mechanics/RbBodyFrame.h", "chrono/physics/ChBodyFrame.h"),
    ("robodyna/mechanics/RbPhysicsItem.h", "chrono/physics/ChPhysicsItem.h"),
    ("robodyna/mbd/RbBody.h", "chrono/physics/ChBody.h"),
    ("robodyna/mbd/RbBodyAuxRef.h", "chrono/physics/ChBodyAuxRef.h"),
    ("robodyna/mbd/RbLinkTSDA.h", "chrono/physics/ChLinkTSDA.h"),
    ("robodyna/mbd/RbBodyEasy.h", "chrono/physics/ChBodyEasy.h"),
    ("robodyna/fea/RbMesh.h", "chrono/fea/ChMesh.h"),
    ("robodyna/fea/RbNodeFEAxyz.h", "chrono/fea/ChNodeFEAxyz.h"),
    ("robodyna/fea/RbElementSpring.h", "chrono/fea/ChElementSpring.h"),
    ("robodyna/simulation/RbSystem.h", "chrono/physics/ChSystem.h"),
    ("robodyna/simulation/RbSystemNSC.h", "chrono/physics/ChSystemNSC.h"),
    ("robodyna/simulation/RbSystemSMC.h", "chrono/physics/ChSystemSMC.h"),
    ("robodyna/simulation/RbAssembly.h", "chrono/physics/ChAssembly.h"),
    ("robodyna/contact/RbContactMaterial.h", "chrono/physics/ChContactMaterial.h"),
    ("robodyna/contact/RbContactMaterialNSC.h", "chrono/physics/ChContactMaterialNSC.h"),
    ("robodyna/contact/RbContactMaterialSMC.h", "chrono/physics/ChContactMaterialSMC.h"),
    ("robodyna/numerics/RbSolver.h", "chrono/solver/ChSolver.h"),
    ("robodyna/numerics/RbSolverPSOR.h", "chrono/solver/ChSolverPSOR.h"),
    ("robodyna/numerics/RbSolverMINRES.h", "chrono/solver/ChIterativeSolverLS.h"),
    ("robodyna/numerics/RbTimestepper.h", "chrono/timestepper/ChTimestepper.h"),
    ("robodyna/numerics/RbTimestepperEulerImplicit.h", "chrono/timestepper/ChTimestepperImplicit.h"),
]
