#!/usr/bin/env python3
"""Generate/check the bounded NPT=3 elastic K2 adaptation from pinned originals.

No donor is edited. No unpinned-input override exists. Run CPU work through the
shared workstation guard. This generator does not qualify any constitutive law.
"""
import argparse
import difflib
import hashlib
import json
import math
import os
from pathlib import Path
import re
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[4]
QUALIFICATION = Path(__file__).resolve().parent.parent
DONOR_DEFAULT = QUALIFICATION / 'reference/cuda'
TABLE_DEFAULT = ROOT / 'lib_utils/quadrature_utils.h'
OUTPUT_DEFAULT = Path(__file__).resolve().parent / 'generated'
REVISION = 'a62b27e6baa555d222a580d6218867d0be4d70b5'
TABLE_SHA = '1bb073cfc14ff2fe9a4c2bcc48b7c1a875133f4ed8242276d39ba929ce690f51'
DONOR_PINS = {
    'shell_geometry_kernel.cu': 'e5c8a9609aff7f42854062b30204645f9ba3d918b31d2aeb5cb40beab0d52430',
    'shell_geometry_kernel.h': 'b429eb23b52f98d0cb347592f7cfb3ab936deb029b5cbe1d7cb7cab5cd96adf2',
    'shell_force_assembly_kernel.cu': '411db646e3070ade11ad217e68e6326f5e6604e3ede4e0402ebb4b03b0004ea8',
    'shell_force_assembly_kernel.h': '06f474d1c859391eef88013c914886a1da5d889fca8dcbe5d9fca7c10ef4a10c',
    'shell_strain_material_kernel.cu': '13ebd98348f91919f5bf81f6d3932f5a19039504611608bc0e6d2194080fd0ba',
    'shell_strain_material_kernel.h': 'c599a32b33c10bbf597565d26998713dc88716fe6b52757b148b1273a98bf830',
    'real_type.h': '057c418c48ad7e771f9dd125f2461104628631d6e6f80aa73f1ff910bdc01796',
    'LICENSE.md': 'ad858d53cae05eed9531ecd4c467440803acffe34c69de7b88e03affc5b6a1bd',
}
SOURCE_NAME = 'shell_strain_material_kernel_gauss3.cu'
HEADER_NAME = 'shell_thickness_gauss3.h'
INCLUDE_ANCHOR = '#include "real_type.h"'
ZETA_ANCHOR = '        Real zeta = -0.5 + ((Real)ipt + 0.5) / (Real)NPT;'
WEIGHT_ANCHOR = '        Real wt = thk0_i / (Real)NPT;'
REPLACEMENTS = (
    (INCLUDE_ANCHOR, INCLUDE_ANCHOR + '\n'
     '// Local modification 2026-09-08: NPT=3 Gauss thickness rule; see generated manifest.json.\n'
     '#include "' + HEADER_NAME + '"'),
    (ZETA_ANCHOR, '        Real zeta = (NPT == 3) ? crash_shell_gauss3::zeta(ipt)\n'
     '                               : -0.5 + ((Real)ipt + 0.5) / (Real)NPT;'),
    (WEIGHT_ANCHOR, '        Real wt = (NPT == 3) ? thk0_i * crash_shell_gauss3::weight(ipt)\n'
     '                             : thk0_i / (Real)NPT;'),
)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def read_pinned(path, expected):
    data = path.read_bytes()
    actual = sha(data)
    if actual != expected:
        raise ValueError(f'Pinned input hash mismatch: {path}; expected {expected}, got {actual}')
    return data


def replace_exactly_once(text, old, new):
    count = text.count(old)
    if count != 1:
        raise ValueError(f'Transformation anchor count must be 1, got {count}: {old}')
    return text.replace(old, new, 1)


def transform(source):
    for old, new in REPLACEMENTS:
        source = replace_exactly_once(source, old, new)
    return source


def extract_literals(text, name):
    matches = re.findall(r'const Eigen::VectorXd\s+' + re.escape(name)
                         + r'\s*=\s*\(Eigen::VectorXd\(N_QP_3\)\s*<<([^)]*)\)', text)
    if len(matches) != 1:
        raise ValueError('Expected exactly one three-point TL table: ' + name)
    literals = [value.strip() for value in matches[0].split(',')]
    if len(literals) != 3 or any(not re.fullmatch(r'-?\d+\.\d+', value) for value in literals):
        raise ValueError('Unexpected literal syntax in TL table: ' + name)
    return literals


def make_header(table):
    nodes = extract_literals(table, 'gauss_zeta_m_3')
    weights = extract_literals(table, 'weight_zeta_m_3')
    values = [(float(x) / 2, float(w) / 2) for x, w in zip(nodes, weights)]
    # Independent polynomial identity guards the mapping, not merely the hash.
    for degree in range(6):
        exact = ((0.5 ** (degree + 1)) - ((-0.5) ** (degree + 1))) / (degree + 1)
        measured = math.fsum(w * x ** degree for x, w in values)
        if abs(measured - exact) > 2e-16:
            raise ValueError('TL table fails unit-thickness polynomial identity')
    text = ('// Generated by generate_gauss3.py; do not edit.\n'
            '// Numerical values reused from Total-Lagrangian-FEA/lib_utils/quadrature_utils.h\n'
            '// gauss_zeta_m_3 and weight_zeta_m_3, SHA256 ' + TABLE_SHA + '.\n'
            '// Isolated elastic fixture adapter for pinned OpenRadioss K2; see manifest.json.\n'
            '// Existing [-1,1] table maps to unit thickness [-1/2,1/2].\n'
            '#pragma once\n\n#include "real_type.h"\n\n'
            'namespace crash_shell_gauss3 {\n'
            '__device__ __forceinline__ Real zeta(int ipt) {\n'
            '    constexpr Real nodes[3] = {' + ', '.join(nodes) + '};\n'
            '    return Real(0.5) * nodes[ipt];\n}\n'
            '__device__ __forceinline__ Real weight(int ipt) {\n'
            '    constexpr Real weights[3] = {' + ', '.join(weights) + '};\n'
            '    return Real(0.5) * weights[ipt];\n}\n'
            '}  // namespace crash_shell_gauss3\n')
    return text, nodes, weights


def build_artifacts(donor_dir, table_path):
    donor = {name: read_pinned(donor_dir / name, pin) for name, pin in DONOR_PINS.items()}
    source_manifest_bytes = (donor_dir / 'source-manifest.json').read_bytes()
    source_manifest = json.loads(source_manifest_bytes)
    listed = source_manifest['files']
    if (source_manifest['revision'] != REVISION
            or source_manifest['origin'] != 'https://github.com/OpenRadioss/OpenRadioss'
            or len(listed) != len(DONOR_PINS)
            or {entry['file']: entry['sha256'] for entry in listed} != DONOR_PINS
            or any(entry['bytes'] != len(donor[entry['file']]) for entry in listed)):
        raise ValueError('Original donor manifest does not match the pinned input inventory')
    table = read_pinned(table_path, TABLE_SHA).decode('utf-8')
    original = donor['shell_strain_material_kernel.cu'].decode('utf-8')
    corrected = transform(original)
    header, nodes, weights = make_header(table)
    artifacts = {SOURCE_NAME: corrected.encode('utf-8'), HEADER_NAME: header.encode('utf-8'),
                 'LICENSE.md': donor['LICENSE.md'],
                 'transformation.patch': ''.join(difflib.unified_diff(
                     original.splitlines(keepends=True), corrected.splitlines(keepends=True),
                     fromfile='a/donor/shell_strain_material_kernel.cu',
                     tofile='b/generated/' + SOURCE_NAME)).encode('utf-8')}
    manifest = dict(schema_version=1, scope='NPT=3 Gauss thickness coordinates and stress-resultant '
                    'weights in an isolated elastic fixture. No plasticity, MAT024, full-K2, '
                    'or vehicle admission is implied.', generated_file=SOURCE_NAME,
                    donor=dict(origin='https://github.com/OpenRadioss/OpenRadioss', revision=REVISION,
                               original_path='engine/source/elements/shell/coque/shell_strain_material_kernel.cu',
                               files_sha256=DONOR_PINS, originals_modified=False,
                               source_manifest_sha256=sha(source_manifest_bytes),
                               license='GNU AGPL version 3 or later; original notice retained; exact LICENSE.md included'),
                    table=dict(path='Total-Lagrangian-FEA/lib_utils/quadrature_utils.h', sha256=TABLE_SHA,
                               nodes_symbol='Quadrature::gauss_zeta_m_3', weights_symbol='Quadrature::weight_zeta_m_3',
                               original_node_literals=nodes, original_weight_literals=weights,
                               mapping='z=h0*xi/2; physical_weight=h0*w/2'),
                    generator=dict(path='lib_utest/qualification/shell/operators/generate_gauss3.py',
                                   sha256=sha(Path(__file__).read_bytes()), local_change_date='2026-09-08'),
                    transformations=[dict(original=old, replacement=new, required_count=1) for old, new in REPLACEMENTS],
                    contracts=dict(allowed_fixture_NPT=[3], required_define='MYREAL8',
                                   other_NPT_branches='original expressions retained, not qualified',
                                   material='synthetic homogeneous plane-stress elastic predictor only',
                                   state='Per-point layout and all history updates unchanged; initialize fresh Gauss states; '
                                   'never relabel/restart existing midpoint histories.',
                                   unchanged_thickness_update='Equal h0/NPT layer measure retained; exact for the '
                                   'bounded affine elastic thickness-strain field; nonlinear layer audit pending.',
                                   original_comments='Historical donor quadrature comments are retained; local header '
                                   'and this manifest identify the NPT3 change precisely.'),
                    outputs={name: dict(sha256=sha(data), bytes=len(data)) for name, data in sorted(artifacts.items())})
    artifacts['manifest.json'] = (json.dumps(manifest, indent=2, sort_keys=True) + '\n').encode('utf-8')
    artifacts['SHA256SUMS'] = ''.join(f'{sha(data)}  {name}\n' for name, data in sorted(artifacts.items())).encode('ascii')
    return artifacts


def check_artifacts(output, artifacts):
    for name, expected in artifacts.items():
        path = output / name
        if not path.is_file() or path.read_bytes() != expected:
            raise ValueError('Generated artifact missing or inconsistent: ' + str(path))


def verify_migration(directory=QUALIFICATION):
    """Check the captured relocation inventory without reading crash-work."""
    manifest = json.loads((directory / 'migration-manifest.json').read_bytes())
    if manifest['schema_version'] != 1 or not manifest['files']:
        raise ValueError('Invalid shell migration manifest')
    seen = set()
    for entry in manifest['files']:
        relative = Path(entry['path'])
        if relative.is_absolute() or '..' in relative.parts or str(relative) in seen:
            raise ValueError('Invalid or duplicate migration path')
        seen.add(str(relative))
        path = directory / relative
        data = path.read_bytes()
        if len(data) != entry['bytes'] or sha(data) != entry['sha256']:
            raise ValueError('Migrated source differs from captured checkpoint: ' + str(relative))
        if entry['kind'] == 'byte-identical':
            if entry['sha256'] != entry['original_sha256']:
                raise ValueError('Migration changed preserved source bytes: ' + str(relative))
        elif entry['kind'] != 'build-path-provenance-only':
            raise ValueError('Unknown migration change category')
    return len(seen)


def write_artifacts(output, artifacts, donor_dir):
    target, source = output.resolve(), donor_dir.resolve()
    if target == source or target in source.parents or source in target.parents:
        raise ValueError('Generated output must be separate from original donor directory')
    output.mkdir(parents=True, exist_ok=True)
    # Prepare every file before publication. Parent serializes generation/builds.
    with tempfile.TemporaryDirectory(prefix='.gauss3-stage-', dir=output.parent) as staging:
        for name, data in artifacts.items():
            (Path(staging) / name).write_bytes(data)
        for name in artifacts:
            os.replace(Path(staging) / name, output / name)
    check_artifacts(output, artifacts)


class GeneratorTests(unittest.TestCase):
    donor = DONOR_DEFAULT
    table = TABLE_DEFAULT

    def test_donor_hash_drift_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            altered = Path(directory)
            for name in DONOR_PINS:
                data = (self.donor / name).read_bytes()
                if name == 'shell_strain_material_kernel.cu':
                    data += b'\n// changed donor\n'
                (altered / name).write_bytes(data)
            with self.assertRaisesRegex(ValueError, 'Pinned input hash mismatch'):
                build_artifacts(altered, self.table)

    def test_table_hash_drift_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            altered = Path(directory) / 'table.h'
            altered.write_bytes(self.table.read_bytes() + b'\n')
            with self.assertRaisesRegex(ValueError, 'Pinned input hash mismatch'):
                build_artifacts(self.donor, altered)

    def test_original_manifest_drift_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            altered = Path(directory)
            for name in DONOR_PINS:
                (altered / name).write_bytes((self.donor / name).read_bytes())
            source_manifest = json.loads((self.donor / 'source-manifest.json').read_bytes())
            source_manifest['revision'] = 'wrong-revision'
            (altered / 'source-manifest.json').write_text(json.dumps(source_manifest))
            with self.assertRaisesRegex(ValueError, 'Original donor manifest'):
                build_artifacts(altered, self.table)

    def test_missing_and_duplicate_anchors_rejected(self):
        original = (self.donor / 'shell_strain_material_kernel.cu').read_text()
        for anchor, _ in REPLACEMENTS:
            for modified in (original.replace(anchor, '', 1), original + '\n' + anchor):
                with self.subTest(anchor=anchor), self.assertRaisesRegex(ValueError, 'anchor count'):
                    transform(modified)

    def test_exactly_three_changes_reversible(self):
        original = (self.donor / 'shell_strain_material_kernel.cu').read_text()
        corrected = transform(original)
        for old, new in reversed(REPLACEMENTS):
            corrected = replace_exactly_once(corrected, new, old)
        self.assertEqual(corrected, original)

    def test_table_literal_reuse_and_mapping(self):
        header, nodes, weights = make_header(self.table.read_text())
        self.assertIn('Real(0.5) * nodes[ipt]', header)
        self.assertIn('Real(0.5) * weights[ipt]', header)
        self.assertEqual(nodes, ['-0.7745966692414834', '0.0', '0.7745966692414834'])
        self.assertEqual(weights, ['0.5555555555555556', '0.8888888888888888', '0.5555555555555556'])
        with self.assertRaises(ValueError):
            make_header(self.table.read_text().replace('0.7745966692414834', '0.1'))

    def test_deterministic_artifacts_and_output_tamper_detection(self):
        first = build_artifacts(self.donor, self.table)
        self.assertEqual(first, build_artifacts(self.donor, self.table))
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / 'generated'
            write_artifacts(output, first, self.donor)
            check_artifacts(output, first)
            for name in first:
                path = output / name
                path.write_bytes(first[name] + b'changed')
                with self.subTest(name=name), self.assertRaisesRegex(ValueError, 'inconsistent'):
                    check_artifacts(output, first)
                path.write_bytes(first[name])
            for name, data in first.items():
                self.assertEqual((output / name).read_bytes(), data)

    def test_original_license_and_no_donor_overwrite(self):
        artifacts = build_artifacts(self.donor, self.table)
        self.assertEqual(artifacts['LICENSE.md'], (self.donor / 'LICENSE.md').read_bytes())
        source_notice = (self.donor / 'shell_strain_material_kernel.cu').read_bytes().split(b'#ifndef')[0]
        self.assertTrue(artifacts[SOURCE_NAME].startswith(source_notice))
        with self.assertRaisesRegex(ValueError, 'separate from original'):
            write_artifacts(self.donor, artifacts, self.donor)

    def test_migration_source_drift_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            data = b'captured fixture checkpoint\n'
            entry = dict(path='fixture.cu', bytes=len(data), sha256=sha(data),
                         original_sha256=sha(data), kind='byte-identical')
            (root / 'migration-manifest.json').write_text(json.dumps(
                dict(schema_version=1, files=[entry])))
            source = root / 'fixture.cu'
            source.write_bytes(data)
            self.assertEqual(verify_migration(root), 1)
            source.write_bytes(data + b'changed')
            with self.assertRaisesRegex(ValueError, 'checkpoint'):
                verify_migration(root)

    def test_migration_false_preservation_claim_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            data = b'locally changed fixture\n'
            entry = dict(path='fixture.cu', bytes=len(data), sha256=sha(data),
                         original_sha256=sha(b'original fixture\n'), kind='byte-identical')
            (root / 'migration-manifest.json').write_text(json.dumps(
                dict(schema_version=1, files=[entry])))
            (root / 'fixture.cu').write_bytes(data)
            with self.assertRaisesRegex(ValueError, 'preserved source'):
                verify_migration(root)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--donor-dir', type=Path, default=DONOR_DEFAULT)
    parser.add_argument('--table-path', type=Path, default=TABLE_DEFAULT)
    parser.add_argument('--output', type=Path, default=OUTPUT_DEFAULT)
    parser.add_argument('--check', '--verify', action='store_true', help='Read-only exact generated-output consistency check')
    parser.add_argument('--self-test', action='store_true', help='Run bounded transformation regression tests first')
    args = parser.parse_args()
    if args.self_test:
        GeneratorTests.donor, GeneratorTests.table = args.donor_dir, args.table_path
        tests = unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(GeneratorTests))
        if not tests.wasSuccessful():
            raise SystemExit(1)
    artifacts = build_artifacts(args.donor_dir, args.table_path)
    if args.check:
        check_artifacts(args.output, artifacts)
        verify_migration()
    else:
        write_artifacts(args.output, artifacts, args.donor_dir)
    print(json.dumps(dict(status='verified' if args.check else 'generated', output=str(args.output),
                          files=sorted(artifacts), corrected_K2_sha256=sha(artifacts[SOURCE_NAME]),
                          donor_modified=False, qualified_solver=False), indent=2))


if __name__ == '__main__':
    main()
