"""Retained OptiX source partition; Vulkan/Metal and NanoVDB are not selected."""

OPTIX_PROFILE = {'CH_USE_SENSOR_OPTIX': True,
 'CH_USE_SENSOR_VULKAN_RT': False,
 'CH_USE_SENSOR_VULKAN_RT_GPU': False,
 'CH_USE_SENSOR_METAL_RT': False,
 'CH_USE_SENSOR_NVDB': False,
 'CH_ENABLE_MODULE_FSI_SPH': True}

OPTIX_HOST_GROUPS = {'management': {'cmake_group': 'Chrono_sensor',
                'sources': ['src/chrono_sensor/ChSensorManager.cpp', 'src/chrono_sensor/ChDynamicsManager.cpp'],
                'headers': ['src/chrono_sensor/ChApiSensor.h',
                            'src/chrono_sensor/ChSensorManager.h',
                            'src/chrono_sensor/ChDynamicsManager.h',
                            'src/chrono_sensor/ChFsiSphRender.h',
                            'src/chrono_sensor/ChSensorRenderTypes.h']},
 'sensors': {'cmake_group': 'Chrono_sensor_SENSORS',
             'sources': ['src/chrono_sensor/sensors/ChSensor.cpp',
                         'src/chrono_sensor/sensors/ChNoiseModel.cpp',
                         'src/chrono_sensor/sensors/ChIMUSensor.cpp',
                         'src/chrono_sensor/sensors/ChGPSSensor.cpp',
                         'src/chrono_sensor/sensors/ChTachometerSensor.cpp',
                         'src/chrono_sensor/sensors/Sensor.cpp',
                         'src/chrono_sensor/sensors/ChOptixSensor.cpp',
                         'src/chrono_sensor/sensors/ChCameraSensor.cpp',
                         'src/chrono_sensor/sensors/ChPhysCameraSensor.cpp',
                         'src/chrono_sensor/sensors/ChSegmentationCamera.cpp',
                         'src/chrono_sensor/sensors/ChDepthCamera.cpp',
                         'src/chrono_sensor/sensors/ChNormalCamera.cpp',
                         'src/chrono_sensor/sensors/ChLidarSensor.cpp',
                         'src/chrono_sensor/sensors/ChRadarSensor.cpp'],
             'headers': ['src/chrono_sensor/sensors/ChSensor.h',
                         'src/chrono_sensor/sensors/ChNoiseModel.h',
                         'src/chrono_sensor/sensors/ChIMUSensor.h',
                         'src/chrono_sensor/sensors/ChGPSSensor.h',
                         'src/chrono_sensor/sensors/ChTachometerSensor.h',
                         'src/chrono_sensor/sensors/ChSensorBuffer.h',
                         'src/chrono_sensor/sensors/Sensor.h',
                         'src/chrono_sensor/sensors/ChOptixSensor.h',
                         'src/chrono_sensor/sensors/ChCameraSensor.h',
                         'src/chrono_sensor/sensors/ChPhysCameraSensor.h',
                         'src/chrono_sensor/sensors/ChSegmentationCamera.h',
                         'src/chrono_sensor/sensors/ChDepthCamera.h',
                         'src/chrono_sensor/sensors/ChNormalCamera.h',
                         'src/chrono_sensor/sensors/ChLidarSensor.h',
                         'src/chrono_sensor/sensors/ChRadarSensor.h']},
 'filters': {'cmake_group': 'Chrono_sensor_FILTERS',
             'sources': ['src/chrono_sensor/filters/ChFilter.cpp',
                         'src/chrono_sensor/filters/ChFilterAccess.cpp',
                         'src/chrono_sensor/filters/ChFilterIMUUpdate.cpp',
                         'src/chrono_sensor/filters/ChFilterGPSUpdate.cpp',
                         'src/chrono_sensor/filters/ChFilterTachometerUpdate.cpp',
                         'src/chrono_sensor/filters/ChFilterCameraNoise.cpp',
                         'src/chrono_sensor/filters/ChFilterGrayscale.cpp',
                         'src/chrono_sensor/filters/ChFilterImageOps.cpp',
                         'src/chrono_sensor/filters/ChFilterVisualize.cpp',
                         'src/chrono_sensor/filters/ChFilterSave.cpp',
                         'src/chrono_sensor/filters/ChFilterCameraExposure.cpp',
                         'src/chrono_sensor/filters/ChFilterLidarNoise.cpp',
                         'src/chrono_sensor/filters/ChFilterLidarIntensityClip.cpp',
                         'src/chrono_sensor/filters/ChFilterLidarReduce.cpp',
                         'src/chrono_sensor/filters/ChFilterPCfromDepth.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarProcess.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarXYZReturn.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarSavePC.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarXYZVisualize.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarVisualizeCluster.cpp',
                         'src/chrono_sensor/filters/ChFilterSavePtCloud.cpp',
                         'src/chrono_sensor/filters/ChFilterVisualizePointCloud.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraDefocusBlur.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraVignetting.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraAggregator.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraNoise.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraExpsrToDV.cpp'],
             'headers': ['src/chrono_sensor/filters/ChFilter.h',
                         'src/chrono_sensor/filters/ChFilterAccess.h',
                         'src/chrono_sensor/filters/ChFilterIMUUpdate.h',
                         'src/chrono_sensor/filters/ChFilterGPSUpdate.h',
                         'src/chrono_sensor/filters/ChFilterTachometerUpdate.h',
                         'src/chrono_sensor/filters/ChFilterCameraNoise.h',
                         'src/chrono_sensor/filters/ChFilterGrayscale.h',
                         'src/chrono_sensor/filters/ChFilterImageOps.h',
                         'src/chrono_sensor/filters/ChFilterVisualize.h',
                         'src/chrono_sensor/filters/ChFilterSave.h',
                         'src/chrono_sensor/filters/ChFilterCameraExposure.h',
                         'src/chrono_sensor/filters/ChFilterLidarNoise.h',
                         'src/chrono_sensor/filters/ChFilterLidarReduce.h',
                         'src/chrono_sensor/filters/ChFilterLidarIntensityClip.h',
                         'src/chrono_sensor/filters/ChFilterPCfromDepth.h',
                         'src/chrono_sensor/filters/ChFilterRadarProcess.h',
                         'src/chrono_sensor/filters/ChFilterRadarXYZReturn.h',
                         'src/chrono_sensor/filters/ChFilterRadarSavePC.h',
                         'src/chrono_sensor/filters/ChFilterRadarXYZVisualize.h',
                         'src/chrono_sensor/filters/ChFilterRadarVisualizeCluster.h',
                         'src/chrono_sensor/filters/ChFilterSavePtCloud.h',
                         'src/chrono_sensor/filters/ChFilterVisualizePointCloud.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraDefocusBlur.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraVignetting.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraAggregator.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraNoise.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraExpsrToDV.h']},
 'utilities': {'cmake_group': 'Chrono_sensor_UTILS',
               'sources': ['src/chrono_sensor/utils/ChSensorUtils.cpp',
                           'src/chrono_sensor/utils/ChSensorUtilsJSON.cpp',
                           'src/chrono_sensor/utils/ChGPSUtils.cpp',
                           'src/chrono_sensor/utils/Kdtree.cpp',
                           'src/chrono_sensor/utils/Dbscan.cpp'],
               'headers': ['src/chrono_sensor/utils/ChSensorUtils.h',
                           'src/chrono_sensor/utils/ChSensorUtilsJSON.h',
                           'src/chrono_sensor/utils/ChGPSUtils.h',
                           'src/chrono_sensor/utils/Kdtree.h',
                           'src/chrono_sensor/utils/Dbscan.h',
                           'src/chrono_sensor/utils/CudaMallocHelper.h']},
 'optix': {'cmake_group': 'Chrono_sensor_OPTIX',
           'sources': ['src/chrono_sensor/optix/ChOptixEngine.cpp',
                       'src/chrono_sensor/optix/ChOptixGeometry.cpp',
                       'src/chrono_sensor/optix/ChOptixPipeline.cpp',
                       'src/chrono_sensor/optix/ChOptixUtils.cpp',
                       'src/chrono_sensor/optix/ChOptixScene.cpp',
                       'src/chrono_sensor/optix/ChFilterOptixRender.cpp',
                       'src/chrono_sensor/optix/ChNVDBVolume.cpp'],
           'headers': ['src/chrono_sensor/optix/ChOptixEngine.h',
                       'src/chrono_sensor/optix/ChOptixGeometry.h',
                       'src/chrono_sensor/optix/ChOptixPipeline.h',
                       'src/chrono_sensor/optix/ChOptixUtils.h',
                       'src/chrono_sensor/optix/ChOptixScene.h',
                       'src/chrono_sensor/optix/ChFilterOptixRender.h',
                       'src/chrono_sensor/optix/ChOptixDefinitions.h',
                       'src/chrono_sensor/optix/ChNVDBVolume.h']}}

OPTIX_CUDA_SOURCES = ['src/chrono_sensor/cuda/grayscale.cu',
 'src/chrono_sensor/cuda/pointcloud.cu',
 'src/chrono_sensor/cuda/lidar_reduce.cu',
 'src/chrono_sensor/cuda/camera_noise.cu',
 'src/chrono_sensor/cuda/lidar_noise.cu',
 'src/chrono_sensor/cuda/curand_utils.cu',
 'src/chrono_sensor/cuda/image_ops.cu',
 'src/chrono_sensor/cuda/nn_prep.cu',
 'src/chrono_sensor/cuda/lidar_clip.cu',
 'src/chrono_sensor/cuda/radarprocess.cu',
 'src/chrono_sensor/cuda/cuda_utils.cu',
 'src/chrono_sensor/cuda/phys_cam_ops.cu']

OPTIX_SPH_CUDA_SOURCES = ['src/chrono_sensor/cuda/fsi_sph_render.cu']

OPTIX_CUDA_SHADER_HEADERS = ['src/chrono_sensor/cuda/camera_noise.cuh',
 'src/chrono_sensor/cuda/cuda_utils.cuh',
 'src/chrono_sensor/cuda/curand_utils.cuh',
 'src/chrono_sensor/cuda/fsi_sph_render.cuh',
 'src/chrono_sensor/cuda/grayscale.cuh',
 'src/chrono_sensor/cuda/image_ops.cuh',
 'src/chrono_sensor/cuda/lidar_clip.cuh',
 'src/chrono_sensor/cuda/lidar_noise.cuh',
 'src/chrono_sensor/cuda/lidar_reduce.cuh',
 'src/chrono_sensor/cuda/nn_prep.cuh',
 'src/chrono_sensor/cuda/phys_cam_ops.cuh',
 'src/chrono_sensor/cuda/radarprocess.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixDirectionalLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixDiskLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixEnvironmentLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixLightHubs.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixLightStructs.h',
 'src/chrono_sensor/optix/shaders/ChOptixPointLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixRectangleLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixSpotLight.cuh',
 'src/chrono_sensor/optix/shaders/camera_hapke_shader.cuh',
 'src/chrono_sensor/optix/shaders/camera_legacy_shader.cuh',
 'src/chrono_sensor/optix/shaders/camera_path_shader.cuh',
 'src/chrono_sensor/optix/shaders/camera_shader.cuh',
 'src/chrono_sensor/optix/shaders/camera_utils.cuh',
 'src/chrono_sensor/optix/shaders/camera_volumetric_shader.cuh',
 'src/chrono_sensor/optix/shaders/depth_cam_shader.cuh',
 'src/chrono_sensor/optix/shaders/device_utils.cuh',
 'src/chrono_sensor/optix/shaders/lidar_shader.cuh',
 'src/chrono_sensor/optix/shaders/normal_cam_shader.cuh',
 'src/chrono_sensor/optix/shaders/radar_shader.cuh',
 'src/chrono_sensor/optix/shaders/segment_cam_shader.cuh',
 'src/chrono_sensor/optix/shaders/shader_utils.cuh',
 'src/chrono_sensor/optix/shaders/shadow_shader.cuh']

OPTIX_PRIVATE_HEADERS = ['src/chrono_sensor/cuda/pointcloud.cuh',
 'src/chrono_sensor/filters/ChFilterVisualizeGuards.h',
 'src/chrono_sensor/utils/ChSensorImageCompare.h']

OPTIX_RUNTIME_SHADERS = ['src/chrono_sensor/optix/shaders/box.cu',
 'src/chrono_sensor/optix/shaders/sphere.cu',
 'src/chrono_sensor/optix/shaders/cylinder.cu',
 'src/chrono_sensor/optix/shaders/miss.cu',
 'src/chrono_sensor/optix/shaders/material_shaders.cu',
 'src/chrono_sensor/optix/shaders/camera_raygen.cu',
 'src/chrono_sensor/optix/shaders/depth_cam_raygen.cu',
 'src/chrono_sensor/optix/shaders/lidar_raygen.cu',
 'src/chrono_sensor/optix/shaders/normal_cam_raygen.cu',
 'src/chrono_sensor/optix/shaders/phys_cam_raygen.cu',
 'src/chrono_sensor/optix/shaders/radar_raygen.cu',
 'src/chrono_sensor/optix/shaders/segment_cam_raygen.cu']

OPTIX_RUNTIME_HEADERS = ['src/chrono/assets/ChVisualBSDFType.h',
 'src/chrono_sensor/optix/ChOptixDefinitions.h',
 'src/chrono_sensor/optix/shaders/ChOptixDirectionalLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixDiskLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixEnvironmentLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixLightHubs.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixLightStructs.h',
 'src/chrono_sensor/optix/shaders/ChOptixPointLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixRectangleLight.cuh',
 'src/chrono_sensor/optix/shaders/ChOptixSpotLight.cuh',
 'src/chrono_sensor/optix/shaders/camera_hapke_shader.cuh',
 'src/chrono_sensor/optix/shaders/camera_legacy_shader.cuh',
 'src/chrono_sensor/optix/shaders/camera_path_shader.cuh',
 'src/chrono_sensor/optix/shaders/camera_shader.cuh',
 'src/chrono_sensor/optix/shaders/camera_utils.cuh',
 'src/chrono_sensor/optix/shaders/camera_volumetric_shader.cuh',
 'src/chrono_sensor/optix/shaders/depth_cam_shader.cuh',
 'src/chrono_sensor/optix/shaders/device_utils.cuh',
 'src/chrono_sensor/optix/shaders/lidar_shader.cuh',
 'src/chrono_sensor/optix/shaders/normal_cam_shader.cuh',
 'src/chrono_sensor/optix/shaders/radar_shader.cuh',
 'src/chrono_sensor/optix/shaders/segment_cam_shader.cuh',
 'src/chrono_sensor/optix/shaders/shader_utils.cuh',
 'src/chrono_sensor/optix/shaders/shadow_shader.cuh']
