load("@rules_cc//cc:defs.bzl", "cc_library")
cc_library(
    name = "before_distortion",
    hdrs = ["Types.h", "BeforeDistortion.h"],
    deps = ["//lib_src/elements/solid24:force", "//lib_src/elements/solid_common/controlled_hourglass:controlled_hourglass"],
    visibility = ["//visibility:public"],
)
