enable_language(Fortran)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(QBAT_FORCE_NATIVE_CHECKS ON CACHE BOOL "" FORCE)
set(QBAT_FORCE_CUDA_CHECKS OFF CACHE BOOL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../qbat_force" force)
add_library(qbat_mapped_native STATIC native/NativeInitial.F)
target_link_libraries(qbat_mapped_native PUBLIC qbat_force_native)
foreach(property INCLUDE_DIRECTORIES COMPILE_DEFINITIONS COMPILE_OPTIONS)
  get_target_property(value qbat_force_native ${property})
  set_property(TARGET qbat_mapped_native PROPERTY ${property} "${value}")
endforeach()
add_executable(qbat_mapped_native_test NativeTest.cpp ../qbat_force/NativeOracle.cpp)
target_link_libraries(qbat_mapped_native_test PRIVATE tl_qbat_batch_values qbat_mapped_native GTest::gtest_main)
target_compile_options(qbat_mapped_native_test PRIVATE -fno-fast-math -ffp-contract=off)
add_test(NAME qbat_mapped_native COMMAND qbat_mapped_native_test)
add_test(NAME qbat_mapped_native_identity COMMAND "${Python3_EXECUTABLE}" -B
  "${CMAKE_CURRENT_LIST_DIR}/native/verify_sources.py")
set_tests_properties(qbat_mapped_native PROPERTIES RUN_SERIAL TRUE PROCESSORS 1 TIMEOUT 120)
