# Check the product dependency closure before any test executable is added.
function(check_original_source_io_target target)
  if(NOT TARGET "${target}")
    return()
  endif()
  get_target_property(alias "${target}" ALIASED_TARGET)
  if(alias)
    set(target "${alias}")
  endif()
  get_property(seen GLOBAL PROPERTY ORIGINAL_SOURCE_IO_CHECKED_TARGETS)
  if("${target}" IN_LIST seen)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY ORIGINAL_SOURCE_IO_CHECKED_TARGETS "${target}")
  if(target MATCHES "[Gg][Tt]est|gtest")
    message(FATAL_ERROR "Original source I/O product depends on a test target: ${target}")
  endif()
  get_target_property(sources "${target}" SOURCES)
  foreach(source IN LISTS sources)
    if(source MATCHES "(^|/)tests?/|ActualFixture|TestSupport")
      message(FATAL_ERROR "Original source I/O product contains fixture source: ${source}")
    endif()
  endforeach()
  foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    get_target_property(links "${target}" "${property}")
    foreach(link IN LISTS links)
      if(link MATCHES "[Gg][Tt]est|gtest")
        message(FATAL_ERROR "Original source I/O product links a test dependency: ${link}")
      endif()
      string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" dependency "${link}")
      check_original_source_io_target("${dependency}")
    endforeach()
  endforeach()
endfunction()
check_original_source_io_target(robo_dyna_original_source_io)
