include_guard(GLOBAL)
get_filename_component(robo_scene_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${robo_scene_root}/output/ArtifactIO.cmake")
if(NOT EXISTS "${ROBO_DYNA_TL_ROOT}/lib_src/math/Fixed3.h")
  message(FATAL_ERROR "Declared scene reader requires an explicit TL neutral vector source")
endif()
add_library(robo_dyna_native_scene_declared STATIC "${CMAKE_CURRENT_LIST_DIR}/DeclaredSource.cpp")
target_include_directories(robo_dyna_native_scene_declared PUBLIC "${robo_scene_root}" "${ROBO_DYNA_TL_ROOT}")
target_link_libraries(robo_dyna_native_scene_declared PUBLIC robo_dyna_artifact_io)
target_compile_features(robo_dyna_native_scene_declared PUBLIC cxx_std_17)
target_compile_options(robo_dyna_native_scene_declared PRIVATE -fno-fast-math -ffp-contract=off)
