include_guard(GLOBAL)
get_filename_component(robo_scene_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(ROBO_DYNA_TL_ROOT "" CACHE PATH "Explicit qualified TL source checkout")
if(NOT EXISTS "${ROBO_DYNA_TL_ROOT}/lib_src/materials/TabulatedShellPlasticity.h")
  message(FATAL_ERROR "Native scene material bridge requires an explicit TL material source")
endif()
add_library(robo_dyna_native_scene_material STATIC "${CMAKE_CURRENT_LIST_DIR}/MaterialBridge.cpp")
target_include_directories(robo_dyna_native_scene_material PUBLIC "${robo_scene_root}" "${ROBO_DYNA_TL_ROOT}")
target_compile_features(robo_dyna_native_scene_material PUBLIC cxx_std_17)
target_compile_options(robo_dyna_native_scene_material PRIVATE -fno-fast-math -ffp-contract=off)
