load("@rules_cc//cc:defs.bzl", "cc_test")
load("@rules_cuda//cuda:defs.bzl", "cuda_test")
cc_test(
    name = "qbat_force_check",
    size = "small",
    srcs = ["Fixture.h", "MathTest.cpp"],
    copts = ["-std=c++17", "-fno-fast-math", "-ffp-contract=off"],
    deps = ["//lib_src/elements/qbat:force", "//lib_utest/qualification/qbat:fixture", "@googletest//:gtest_main"],
)
cuda_test(
    name = "qbat_force_cuda_check",
    size = "small",
    srcs = ["Fixture.h", "MathCudaTest.cu"],
    copts = ["--std=c++17", "--fmad=false", "--prec-div=true", "--prec-sqrt=true", "--ftz=false"],
    tags = ["exclusive", "gpu"],
    deps = ["//lib_src/elements/qbat:force", "//lib_utest/qualification/qbat:fixture", "@googletest//:gtest_main"],
)
