! SPDX-License-Identifier: AGPL-3.0-or-later
! Serial, bounded ordinary/resolved-coated shell reference. All numerical stages are original
! Fortran; only source-shaped arrays, local controls and readback live here.
subroutine rd_fixed_main_startup(counts,x,node_ids,primary,stiffness,irect,roles,global_ids, &
    neighbors,neighbor_edges,refs,nrefs,start_bound,start_normals,start_bisectors, &
    offsets,incidence,ready_bound,ready_normals,ready_bisectors,floors,warnings,source_roles) bind(C)
  use iso_c_binding
  use startup_native_observation
  use startup_native_names
  use startup_native_mpi
  use startup_native_normal_storage, only: observed_rep30,observed_rem30, &
      observed_ready_rep30,observed_ready_rem30
  implicit none
  integer(c_int),intent(in)::counts(2),node_ids(counts(1)),primary(4,counts(2)),source_roles(counts(2))
  real(c_double),intent(in)::x(3,counts(1)),stiffness(2*counts(2))
  integer(c_int),intent(out)::irect(4,2*counts(2)),roles(2*counts(2)),global_ids(2*counts(2))
  integer(c_int),intent(out)::neighbors(4,2*counts(2)),neighbor_edges(4,2*counts(2))
  integer(c_int),intent(out)::refs(4,2*counts(2)),nrefs,start_bound(8*counts(2))
  integer(c_int),intent(out)::offsets(8*counts(2)+1),incidence(8*counts(2)),ready_bound(8*counts(2))
  real(c_float),intent(out)::start_normals(3,4,2*counts(2)),start_bisectors(3,2,8*counts(2))
  real(c_float),intent(out)::ready_normals(3,4,2*counts(2)),ready_bisectors(3,2,8*counts(2)),floors(4)
  integer(c_int),intent(out)::warnings(4)
  integer::numnod,numels,nspmd,ninter25,nthread
  common /STARTUP_NATIVE_COUNTS/numnod,numels
  common /STARTUP_NATIVE_PARTITION/nspmd,ninter25
  common /STARTUP_NATIVE_THREADS/nthread
  integer::p,g,i,nedge,nfree,nb_free
  integer::msr(counts(1)),mbin(2*counts(2)),ielem(2,2*counts(2))
  integer::adskyn(8*counts(2)+1),iadnor(4,2*counts(2)),mapping(8*counts(2))
  integer::ledge(15,8*counts(2)),actnor(2*counts(2)),tagnod(counts(1))
  integer::tage(2*counts(2)),free_ids(2*counts(2)),free_bound(4,8*counts(2))
  integer::dummy(1),dummy_matrix(1,1),empty_row(4,1),fr_edge(2,2)
  real(c_float)::work_normals(3,4,2*counts(2)),edge_normals(3,8*counts(2))
  real(c_float)::fskyt(3,8*counts(2)),fskyn(3,8*counts(2))
  real(c_double)::edge_stiffness(1)
  character(nchartitle)::title
  type(mpi_comm_nor_struct)::buffers
  call clear_observations()
  numnod=counts(1);numels=0;nspmd=1;ninter25=1;nthread=1
  p=counts(2);g=2*p
  irect=0;irect(:,1:p)=primary;roles=0;roles(1:p)=source_roles
  ! Actual declared source roles3/7 or+/-4/8 select original SH2SURF branches.
  ! Membership/orientation classification is upstream, not synthesized here.
  global_ids=0;neighbors=0;neighbor_edges=0;refs=0;nrefs=0
  start_bound=0;start_normals=0;start_bisectors=0
  ready_bound=0;ready_normals=0;ready_bisectors=0;offsets=0;incidence=0
  mbin=0;ielem=0;adskyn=0;iadnor=0;mapping=0;ledge=0
  dummy=0;dummy_matrix=0;empty_row=0;fr_edge=0;title='bounded native startup reference'
  do i=1,numnod
    msr(i)=i
  end do
  call SH2SURF25(p,irect,0,mbin,roles,g)
  call I25NEIGH(g,0,dummy,irect,empty_row,neighbors,neighbor_edges,global_ids,roles,node_ids, &
      x,1,title,dummy_matrix,nrefs,refs,adskyn,iadnor,p,0,nedge,ledge,start_bound, &
      0.0_c_double,0,dummy,dummy,dummy,dummy,0,dummy,dummy,dummy,1,numnod,msr, &
      dummy_matrix,1,mbin,dummy,ielem,0,0)
  if(nrefs<1.or.nrefs>4*g)error stop 'Native startup reference count exceeds admitted table'
  call rd_startup_csr(g,nrefs,irect,refs,offsets,incidence,mapping)
  ! Full local restart map must retain the first-encounter numbering already
  ! generated by NEIGH. This is observed, never assumed silently.
  do i=1,nrefs
    if(mapping(i)/=i)error stop 'Local native restart changed reference numbering'
  end do
  edge_normals=0
  call I25NORM(g,irect,numnod,x,start_normals,numnod,msr,node_ids,p,roles, &
      neighbors,neighbor_edges,0,ledge,start_bound,refs,start_bisectors,edge_normals,nrefs,0,ielem)
  ready_normals=start_normals
  ! Original MAIN_NORM clears VTX_BISECTOR before its FLAG1 NORMP call.
  ready_bisectors=0;ready_bound=start_bound
  work_normals=0;fskyt=0;fskyn=0;edge_stiffness=0
  actnor=1;tagnod=1;tage=0;free_ids=0;free_bound=0;nfree=0;nb_free=0
  call I25FREE_BOUND(g,neighbors,irect,stiffness,nfree,free_ids)
  call I25NORMP(1,g,p,irect,x,ready_normals,numnod,msr,1,stiffness,edge_stiffness, &
      actnor,roles,tagnod,neighbors,neighbor_edges,dummy_matrix,fr_edge,work_normals,buffers, &
      0,0,ledge,ready_bound,nrefs,refs,dummy_matrix,dummy,ready_bisectors,1,nb_free,free_bound, &
      tage,free_ids,nfree,fskyt,iadnor,0,dummy,dummy,0,fskyn)
  call I25NORMP(1,g,p,irect,x,ready_normals,numnod,msr,1,stiffness,edge_stiffness, &
      actnor,roles,tagnod,neighbors,neighbor_edges,dummy_matrix,fr_edge,work_normals,buffers, &
      0,0,ledge,ready_bound,nrefs,refs,dummy_matrix,dummy,ready_bisectors,2,nb_free,free_bound, &
      tage,free_ids,nfree,fskyt,iadnor,0,dummy,dummy,0,fskyn)
  floors=[observed_rep30,observed_rem30,observed_ready_rep30,observed_ready_rem30]
  warnings=[warning_count,warning_nodes,selector_calls]
end subroutine
