load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility = ["//visibility:public"])
cc_library(name = "quaternion", hdrs = ["Quaternion.h"])
cc_library(name = "fixed3", hdrs = ["Fixed3.h"])
cc_library(name = "fixed3_operations", hdrs = ["Fixed3Operations.h"], deps = [":fixed3", ":quaternion"])
cc_library(name = "symmetric_eigen3", hdrs = ["SymmetricEigen3.h"], deps = [":fixed3", ":quaternion", "@eigen//:eigen"])
cc_library(name = "positive_identity_plus_symmetric3", hdrs = ["PositiveIdentityPlusSymmetric3.h"], deps = [":quaternion"])
cc_library(
    name = "native_symmetric_eigen3",
    hdrs = ["NativeSymmetricEigen3.h"] + glob(["native_symmetric_eigen3/*.h"]),
    deps = [":fixed3", ":quaternion"],
)
