"""Complete Vehicle demo source exports and original local model helpers."""

VEHICLE_DEMO_SOURCES = ['src/demos/vehicle/articulated_vehicle/demo_VEH_ArticulatedVehicle.cpp',
 'src/demos/vehicle/checkpoint/demo_VEH_Checkpoint.cpp',
 'src/demos/vehicle/checkpoint/demo_VEH_Checkpoint_Collision.cpp',
 'src/demos/vehicle/controllers/demo_VEH_Controller_AIDriver.cpp',
 'src/demos/vehicle/controllers/demo_VEH_Controller_DLC.cpp',
 'src/demos/vehicle/cosimulation/demo_VEH_Cosim_Curiosity.cpp',
 'src/demos/vehicle/cosimulation/demo_VEH_Cosim_TrackedVehicle.cpp',
 'src/demos/vehicle/cosimulation/demo_VEH_Cosim_Viper.cpp',
 'src/demos/vehicle/cosimulation/demo_VEH_Cosim_WheelRig.cpp',
 'src/demos/vehicle/cosimulation/demo_VEH_Cosim_WheeledVehicle.cpp',
 'src/demos/vehicle/cosimulation/demo_VEH_Cosim_WheeledVehicle_OMP.cpp',
 'src/demos/vehicle/cosimulation/demo_VEH_Cosim_WheeledVehicle_SPH.cpp',
 'src/demos/vehicle/cosimulation/external/demo_VEH_Cosim_WheelRig_CustomTerrain.cpp',
 'src/demos/vehicle/fmi/cosim/demo_VEH_FMI2_WheeledVehiclePtrain_a.cpp',
 'src/demos/vehicle/fmi/cosim/demo_VEH_FMI2_WheeledVehiclePtrain_b.cpp',
 'src/demos/vehicle/fmi/cosim/demo_VEH_FMI2_WheeledVehicle_a.cpp',
 'src/demos/vehicle/fmi/cosim/demo_VEH_FMI2_WheeledVehicle_b.cpp',
 'src/demos/vehicle/fmi/modex/demo_VEH_FMI2_PathFollower.cpp',
 'src/demos/vehicle/fsi/demo_VEH_FSI_FloatingBlock.cpp',
 'src/demos/vehicle/multicore/demo_VEH_HMMWV_Multicore.cpp',
 'src/demos/vehicle/multicore/demo_VEH_M113_Multicore.cpp',
 'src/demos/vehicle/multicore/demo_VEH_WheelTestRig_Multicore.cpp',
 'src/demos/vehicle/paths/demo_VEH_paths.cpp',
 'src/demos/vehicle/terrain/demo_VEH_CRGTerrain_VSG.cpp',
 'src/demos/vehicle/terrain/demo_VEH_CRMTerrain_MovingPatch.cpp',
 'src/demos/vehicle/terrain/demo_VEH_CRMTerrain_TrackedVehicle.cpp',
 'src/demos/vehicle/terrain/demo_VEH_CRMTerrain_WheeledVehicle.cpp',
 'src/demos/vehicle/terrain/demo_VEH_GranularTerrain_MovingPatch.cpp',
 'src/demos/vehicle/terrain/demo_VEH_GranularTerrain_RigidTire.cpp',
 'src/demos/vehicle/terrain/demo_VEH_RigidSCMTerrain_MixedPatches.cpp',
 'src/demos/vehicle/terrain/demo_VEH_RigidTerrain_MovingPatch.cpp',
 'src/demos/vehicle/terrain/demo_VEH_RigidTerrain_WheeledVehicle.cpp',
 'src/demos/vehicle/terrain/demo_VEH_SCMTerrain_FEATire.cpp',
 'src/demos/vehicle/terrain/demo_VEH_SCMTerrain_RigidTire.cpp',
 'src/demos/vehicle/terrain/demo_VEH_SCMTerrain_TrackedVehicle.cpp',
 'src/demos/vehicle/terrain/demo_VEH_SCMTerrain_WheeledVehicle.cpp',
 'src/demos/vehicle/test_rigs/demo_VEH_SuspensionTestRig.cpp',
 'src/demos/vehicle/test_rigs/demo_VEH_TrackTestRig.cpp',
 'src/demos/vehicle/test_rigs/demo_VEH_TrackTestRig_Band.cpp',
 'src/demos/vehicle/test_rigs/demo_VEH_WheelSuspensionTestRig.cpp',
 'src/demos/vehicle/test_rigs/demo_VEH_WheelTestRig.cpp',
 'src/demos/vehicle/test_rigs/demo_VEH_WheelTestRig_CRM.cpp',
 'src/demos/vehicle/tracked_models/demo_VEH_M113.cpp',
 'src/demos/vehicle/tracked_models/demo_VEH_M113_Band.cpp',
 'src/demos/vehicle/tracked_models/demo_VEH_Marder.cpp',
 'src/demos/vehicle/tracked_models/demo_VEH_TrackedJSON.cpp',
 'src/demos/vehicle/tracked_models/demo_VEH_TrackedJSON_Band.cpp',
 'src/demos/vehicle/two_cars/demo_VEH_TwoCars.cpp',
 'src/demos/vehicle/visualization/demo_VEH_RenderJSON_VSG.cpp',
 'src/demos/vehicle/wheeled_models/demo_VEH_Gator_Incline.cpp',
 'src/demos/vehicle/wheeled_models/demo_VEH_HMMWV9_YUP.cpp',
 'src/demos/vehicle/wheeled_models/demo_VEH_HMMWV_Rollover.cpp',
 'src/demos/vehicle/wheeled_models/demo_VEH_Sedan_Lockable_Diff.cpp',
 'src/demos/vehicle/wheeled_models/demo_VEH_Wheeled.cpp',
 'src/demos/vehicle/wheeled_models/demo_VEH_WheeledGeneric.cpp',
 'src/demos/vehicle/wheeled_models/demo_VEH_WheeledGenericSet.cpp',
 'src/demos/vehicle/wheeled_models/demo_VEH_WheeledJSON.cpp',
 'src/demos/vehicle/wheeled_tests/demo_VEH_Test_Accel.cpp',
 'src/demos/vehicle/wheeled_tests/demo_VEH_Test_Cornering.cpp',
 'src/demos/vehicle/wheeled_tests/demo_VEH_Test_FEDA_Ride.cpp',
 'src/demos/vehicle/wheeled_tests/demo_VEH_Test_FMTV_Ride.cpp',
 'src/demos/vehicle/wheeled_tests/demo_VEH_Test_ISO2631_Ride.cpp',
 'src/demos/vehicle/wheeled_tests/demo_VEH_Test_ISO2631_Shock.cpp',
 'src/demos/vehicle/wheeled_tests/demo_VEH_Test_TireFEA.cpp']

VEHICLE_DEMO_HEADERS = ['src/demos/SetChronoSolver.h',
 'src/demos/vehicle/WheeledVehicleJSON.h',
 'src/demos/vehicle/WheeledVehicleModels.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_AutomaticTransmissionSimple.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_EngineSimple.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_RigidTire.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_Vehicle.h']

ARTICULATED_SOURCES = ['src/demos/vehicle/articulated_vehicle/subsystems/ACV_AutomaticTransmissionSimple.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_BrakeSimple.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_ChassisConnector.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_ChassisFront.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_ChassisRear.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_Driveline2WD.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_EngineSimple.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_RigidSuspension.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_RigidTire.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_Vehicle.cpp',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_Wheel.cpp']

ARTICULATED_HEADERS = ['src/demos/vehicle/articulated_vehicle/subsystems/ACV_AutomaticTransmissionSimple.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_BrakeSimple.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_ChassisConnector.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_ChassisFront.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_ChassisRear.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_Driveline2WD.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_EngineSimple.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_RigidSuspension.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_RigidTire.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_Vehicle.h',
 'src/demos/vehicle/articulated_vehicle/subsystems/ACV_Wheel.h']

VEHICLE_DEMO_CMAKE_FILES = ['src/demos/vehicle/articulated_vehicle/CMakeLists.txt',
 'src/demos/vehicle/checkpoint/CMakeLists.txt',
 'src/demos/vehicle/controllers/CMakeLists.txt',
 'src/demos/vehicle/cosimulation/CMakeLists.txt',
 'src/demos/vehicle/cosimulation/external/CMakeLists.txt',
 'src/demos/vehicle/fmi/cosim/CMakeLists.txt',
 'src/demos/vehicle/fmi/modex/CMakeLists.txt',
 'src/demos/vehicle/fsi/CMakeLists.txt',
 'src/demos/vehicle/multicore/CMakeLists.txt',
 'src/demos/vehicle/paths/CMakeLists.txt',
 'src/demos/vehicle/terrain/CMakeLists.txt',
 'src/demos/vehicle/test_rigs/CMakeLists.txt',
 'src/demos/vehicle/tracked_models/CMakeLists.txt',
 'src/demos/vehicle/two_cars/CMakeLists.txt',
 'src/demos/vehicle/visualization/CMakeLists.txt',
 'src/demos/vehicle/wheeled_models/CMakeLists.txt',
 'src/demos/vehicle/wheeled_tests/CMakeLists.txt']
