"""Retained distributed-state synchronization source ownership."""

DISTRIBUTED_SOURCES = [
    "src/chrono_synchrono/SynChronoManager.cpp",
    "src/chrono_synchrono/agent/SynAgent.cpp",
    "src/chrono_synchrono/agent/SynAgentFactory.cpp",
    "src/chrono_synchrono/agent/SynCopterAgent.cpp",
    "src/chrono_synchrono/agent/SynEnvironmentAgent.cpp",
    "src/chrono_synchrono/agent/SynSCMTerrainAgent.cpp",
    "src/chrono_synchrono/agent/SynTrackedVehicleAgent.cpp",
    "src/chrono_synchrono/agent/SynWheeledVehicleAgent.cpp",
    "src/chrono_synchrono/communication/SynCommunicator.cpp",
    "src/chrono_synchrono/communication/dds/SynDDSCommunicator.cpp",
    "src/chrono_synchrono/communication/dds/SynDDSListener.cpp",
    "src/chrono_synchrono/communication/dds/SynDDSPublisher.cpp",
    "src/chrono_synchrono/communication/dds/SynDDSSubscriber.cpp",
    "src/chrono_synchrono/communication/dds/SynDDSTopic.cpp",
    "src/chrono_synchrono/communication/dds/idl/SynDDSMessage.cxx",
    "src/chrono_synchrono/communication/dds/idl/SynDDSMessagePubSubTypes.cxx",
    "src/chrono_synchrono/communication/mpi/SynMPICommunicator.cpp",
    "src/chrono_synchrono/controller/SynControllerFunctions.cpp",
    "src/chrono_synchrono/controller/driver/SynMultiPathDriver.cpp",
    "src/chrono_synchrono/flatbuffer/SynFlatBuffersManager.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynApproachMessage.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynCopterMessage.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynEnvironmentMessage.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynMAPMessage.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynMessageFactory.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynMessageUtils.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynSCMMessage.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynSPATMessage.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynSimulationMessage.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynTrackedVehicleMessage.cpp",
    "src/chrono_synchrono/flatbuffer/message/SynWheeledVehicleMessage.cpp",
    "src/chrono_synchrono/utils/SynDataPath.cpp",
    "src/chrono_synchrono/utils/SynGPSTools.cpp",
    "src/chrono_synchrono/utils/SynLog.cpp"
]

DISTRIBUTED_HEADERS = [
    "src/chrono_synchrono/SynApi.h",
    "src/chrono_synchrono/SynChronoManager.h",
    "src/chrono_synchrono/agent/SynAgent.h",
    "src/chrono_synchrono/agent/SynAgentFactory.h",
    "src/chrono_synchrono/agent/SynCopterAgent.h",
    "src/chrono_synchrono/agent/SynEnvironmentAgent.h",
    "src/chrono_synchrono/agent/SynSCMTerrainAgent.h",
    "src/chrono_synchrono/agent/SynTrackedVehicleAgent.h",
    "src/chrono_synchrono/agent/SynWheeledVehicleAgent.h",
    "src/chrono_synchrono/communication/SynCommunicator.h",
    "src/chrono_synchrono/communication/dds/SynDDSCommunicator.h",
    "src/chrono_synchrono/communication/dds/SynDDSListener.h",
    "src/chrono_synchrono/communication/dds/SynDDSPublisher.h",
    "src/chrono_synchrono/communication/dds/SynDDSSubscriber.h",
    "src/chrono_synchrono/communication/dds/SynDDSTopic.h",
    "src/chrono_synchrono/communication/dds/idl/SynDDSMessage.h",
    "src/chrono_synchrono/communication/dds/idl/SynDDSMessagePubSubTypes.h",
    "src/chrono_synchrono/communication/mpi/SynMPICommunicator.h",
    "src/chrono_synchrono/controller/SynControllerFunctions.h",
    "src/chrono_synchrono/controller/driver/SynMultiPathDriver.h",
    "src/chrono_synchrono/flatbuffer/SynFlatBuffersManager.h",
    "src/chrono_synchrono/flatbuffer/message/SynApproachMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynCopterMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynEnvironmentMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynFlatBuffers_generated.h",
    "src/chrono_synchrono/flatbuffer/message/SynMAPMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynMessageFactory.h",
    "src/chrono_synchrono/flatbuffer/message/SynMessageUtils.h",
    "src/chrono_synchrono/flatbuffer/message/SynSCMMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynSPATMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynSimulationMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynTrackedVehicleMessage.h",
    "src/chrono_synchrono/flatbuffer/message/SynWheeledVehicleMessage.h",
    "src/chrono_synchrono/utils/SynDataPath.h",
    "src/chrono_synchrono/utils/SynGPSTools.h",
    "src/chrono_synchrono/utils/SynLog.h"
]

DISTRIBUTED_EXPORTS = DISTRIBUTED_SOURCES + DISTRIBUTED_HEADERS + ["src/chrono_synchrono/CMakeLists.txt", "src/chrono_synchrono/SynConfig.h.in"]

DISTRIBUTED_DEMO_EXPORTS = [
    "src/demos/synchrono/mpi/demo_SYN_scm.cpp",
    "src/demos/synchrono/mpi/demo_SYN_scm_tracked.cpp",
    "src/demos/synchrono/mpi/demo_SYN_wheeled.cpp",
    "src/demos/synchrono/mpi/demo_SYN_tracked.cpp",
    "src/demos/synchrono/mpi/demo_SYN_copter.cpp",
    "src/demos/synchrono/mpi/demo_SYN_highway.cpp",
    "src/demos/synchrono/dds/demo_SYN_DDS_distributed.cpp",
    "src/demos/synchrono/dds/demo_SYN_DDS_wheeled.cpp",
    "src/demos/synchrono/dds/demo_SYN_DDS_tracked.cpp",
    "src/demos/synchrono/CMakeLists.txt",
    "src/demos/synchrono/mpi/CMakeLists.txt",
    "src/demos/synchrono/dds/CMakeLists.txt"
]
