load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "test_feat10_double_pendulum_revolute",
    srcs = ["test_feat10_double_pendulum_revolute.cc"],
    copts = ["--std=c++17"],
    linkopts = [
        "-L/usr/local/cuda/lib64",
        "-lcusparse",
        "-lcudart",
        "-lcudss",
        "-lcublas",
    ],
    deps = [
        "//lib_src/solvers:FEAT10ConstraintManager",
        "//lib_src/elements:FEAT10Data",
        "//lib_src/solvers:solvers_syncednewton",
        "//lib_utils:cpu_utils",
        "//lib_utils:mesh_manager",
        "@eigen//:eigen",
    ],
)

cc_binary(
    name = "test_feat10_double_pendulum_spherical",
    srcs = ["test_feat10_double_pendulum_spherical.cc"],
    copts = ["--std=c++17"],
    linkopts = [
        "-L/usr/local/cuda/lib64",
        "-lcusparse",
        "-lcudart",
        "-lcudss",
        "-lcublas",
    ],
    deps = [
        "//lib_src/solvers:FEAT10ConstraintManager",
        "//lib_src/elements:FEAT10Data",
        "//lib_src/solvers:solvers_syncednewton",
        "//lib_utils:cpu_utils",
        "//lib_utils:mesh_manager",
        "@eigen//:eigen",
    ],
)


cc_binary(
    name = "test_feat10_double_pendulum_welded",
    srcs = ["test_feat10_double_pendulum_welded.cc"],
    copts = ["--std=c++17"],
    linkopts = [
        "-L/usr/local/cuda/lib64",
        "-lcusparse",
        "-lcudart",
        "-lcudss",
        "-lcublas",
    ],
    deps = [
        "//lib_src/solvers:FEAT10ConstraintManager",
        "//lib_src/elements:FEAT10Data",
        "//lib_src/solvers:solvers_syncednewton",
        "//lib_utils:cpu_utils",
        "//lib_utils:mesh_manager",
        "@eigen//:eigen",
    ],
)


cc_binary(
    name = "test_feat10_piston_pump_cylindrical",
    srcs = ["test_feat10_piston_pump_cylindrical.cc"],
    copts = ["--std=c++17"],
    linkopts = [
        "-L/usr/local/cuda/lib64",
        "-lcusparse",
        "-lcudart",
        "-lcudss",
        "-lcublas",
    ],
    deps = [
        "//lib_src/solvers:FEAT10ConstraintManager",
        "//lib_src/elements:FEAT10Data",
        "//lib_src/solvers:solvers_syncednewton",
        "//lib_utils:cpu_utils",
        "//lib_utils:mesh_manager",
        "@eigen//:eigen",
    ],
)
