"""Explicit retained robot model source groups; URDF remains separately gated."""

ROBOT_MODEL_GROUPS = {'common': {'cmake_group': 'CRM_COMMON_FILES',
            'sources': ['src/chrono_models/robot/ChRobotActuation.cpp'],
            'headers': ['src/chrono_models/ChApiModels.h', 'src/chrono_models/robot/ChRobotActuation.h']},
 'robosimian': {'cmake_group': 'CRM_ROBOSIMIAN_FILES',
                'sources': ['src/chrono_models/robot/robosimian/RoboSimian.cpp'],
                'headers': ['src/chrono_models/robot/robosimian/RoboSimian.h']},
 'viper': {'cmake_group': 'CRM_VIPER_FILES',
           'sources': ['src/chrono_models/robot/viper/Viper.cpp'],
           'headers': ['src/chrono_models/robot/viper/Viper.h']},
 'turtlebot': {'cmake_group': 'CRM_TURTLEBOT_FILES',
               'sources': ['src/chrono_models/robot/turtlebot/Turtlebot.cpp'],
               'headers': ['src/chrono_models/robot/turtlebot/Turtlebot.h']},
 'curiosity': {'cmake_group': 'CRM_CURIOSITY_FILES',
               'sources': ['src/chrono_models/robot/curiosity/Curiosity.cpp'],
               'headers': ['src/chrono_models/robot/curiosity/Curiosity.h']},
 'copters': {'cmake_group': 'CRM_COPTERS_FILES',
             'sources': ['src/chrono_models/robot/copters/Little_Hexy.cpp'],
             'headers': ['src/chrono_models/robot/copters/Copter.h',
                         'src/chrono_models/robot/copters/Little_Hexy.h']},
 'industrial': {'cmake_group': 'CRM_INDUSTRIAL_FILES',
                'sources': ['src/chrono_models/robot/industrial/IndustrialRobot.cpp',
                            'src/chrono_models/robot/industrial/IndustrialRobotSCARA.cpp',
                            'src/chrono_models/robot/industrial/IndustrialRobotSCARA_CAD.cpp',
                            'src/chrono_models/robot/industrial/IndustrialRobot6dof.cpp',
                            'src/chrono_models/robot/industrial/IndustrialRobot6dofCAD.cpp',
                            'src/chrono_models/robot/industrial/IndustrialKinematics.cpp',
                            'src/chrono_models/robot/industrial/IndustrialKinematicsSCARA.cpp',
                            'src/chrono_models/robot/industrial/IndustrialKinematics6dofSpherical.cpp',
                            'src/chrono_models/robot/industrial/IndustrialKinematicsNdofNumerical.cpp',
                            'src/chrono_models/robot/industrial/TrajectoryInterpolator.cpp'],
                'headers': ['src/chrono_models/robot/industrial/IndustrialRobot.h',
                            'src/chrono_models/robot/industrial/IndustrialRobotSCARA.h',
                            'src/chrono_models/robot/industrial/IndustrialRobotSCARA_CAD.h',
                            'src/chrono_models/robot/industrial/IndustrialRobot6dof.h',
                            'src/chrono_models/robot/industrial/IndustrialRobot6dofCAD.h',
                            'src/chrono_models/robot/industrial/IndustrialKinematics.h',
                            'src/chrono_models/robot/industrial/IndustrialKinematicsSCARA.h',
                            'src/chrono_models/robot/industrial/IndustrialKinematics6dofSpherical.h',
                            'src/chrono_models/robot/industrial/IndustrialKinematicsNdofNumerical.h',
                            'src/chrono_models/robot/industrial/TrajectoryInterpolator.h']}}

ROBOT_PENDING_URDF = [
    "src/chrono_models/robot/robosimian/RoboSimianURDF.cpp",
    "src/chrono_models/robot/robosimian/RoboSimianURDF.h",
]
