// SPDX-License-Identifier: AGPL-3.0-or-later
// Selected I25ASS0 arithmetic, OpenRadioss Copyright (C) 2026 Siemens.
#pragma once
#include "Endpoints.h"
#include "Schedule.h"
namespace tlfea::contact::radioss_type25::assembly {
// One writer per node, operating only on private candidate nodal scratch.
// The caller authenticates the immutable complete incidence generated by
// BuildIncidence, packet/connectivity versions and all pointer extents. This
// row-local leaf cannot detect an omitted occurrence or forged full-array size.
// Publication requires every node to succeed and the common owner to accept.
template<class Units> TL_MATH_HOST_DEVICE inline Status GatherNode(std::size_t node,
    const Connectivity* rows, const Endpoints<Units>* packets, Schedule schedule,
    Incidence incidence, NodalValue<Units> incoming, NodalValue<Units>* output) {
  if (!output || !incidence.offsets || !incidence.node_count ||
      node >= incidence.node_count || schedule.row_count > UINT32_MAX / 5 ||
      incidence.occurrence_count != 5 * schedule.row_count ||
      (schedule.row_count && (!rows || !packets || !incidence.occurrences)) ||
      !detail::Finite(incoming.force) || !normal_detail::Nonnegative(incoming.stiffness))
    return Status::InvalidInput;
  const auto begin = incidence.offsets[node], end = incidence.offsets[node + 1];
  if (begin > end || end > incidence.occurrence_count) return Status::InvalidInput;
  auto next = incoming;
  std::uint32_t prior_rank = 0;
  for (auto entry = begin; entry < end; ++entry) {
    const auto rank = incidence.occurrences[entry];
    Occurrence at;
    if ((entry != begin && rank <= prior_rank) || !DecodeOccurrence(schedule, rank, &at) ||
        EndpointNode(rows[at.row], at.slot) != node) return Status::InvalidInput;
    prior_rank = rank;
    const auto& packet = packets[at.row];
    if (!packet.active) continue;
    const auto force = at.slot < 4 ? packet.main_force[at.slot] : packet.secondary_resultant;
    const auto stiffness = at.slot < 4 ? packet.main_stiffness[at.slot] : packet.secondary_stiffness;
    if (!detail::Finite(force) || !normal_detail::Nonnegative(stiffness)) return Status::InvalidInput;
    if (at.slot < 4) {
      next.force.x = next.force.x + force.x;
      next.force.y = next.force.y + force.y;
      next.force.z = next.force.z + force.z;
    } else {
      next.force.x = next.force.x - force.x;
      next.force.y = next.force.y - force.y;
      next.force.z = next.force.z - force.z;
    }
    next.stiffness = next.stiffness + stiffness;
    if (!detail::Finite(next.force) || !normal_detail::Nonnegative(next.stiffness))
      return Status::NonfiniteResult;
  }
  *output = next;
  return Status::Ok;
}
} // namespace tlfea::contact::radioss_type25::assembly
