file(READ "${CMAKE_CURRENT_LIST_DIR}/source-manifest.json" receipt)
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/source-manifest.json" receipt_sha)
if(NOT receipt_sha STREQUAL "72688493a88da0348c715ea8af56bab0b700e1a4335e647b814bb14f533f5950")
  message(FATAL_ERROR "Frozen serial scatter receipt differs")
endif()
string(JSON count LENGTH "${receipt}" files)
math(EXPR last "${count}-1")
foreach(index RANGE 0 ${last})
  string(JSON path GET "${receipt}" files ${index} path)
  string(JSON expected GET "${receipt}" files ${index} sha256)
  file(SHA256 "${TL_ROOT}/${path}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Frozen scatter source changed: ${path}")
  endif()
endforeach()
