#pragma once
#include "AssemblyTestSupport.h"

namespace crash::modelio::assembly::test::section {
// Frozen original source compiler products, never regenerated by a reader test.
inline ArtifactIdentity Identity(bool mixed) {
    return mixed ? ArtifactIdentity{1401653,"abcbd5e1ee65e04a4b11ecc712cf4bc89c5402f946fb3eb3fed8801f03ed5a26"}
                 : ArtifactIdentity{285286,"d08a6c68dc429fae38f5a875efab98a1842811bbc89e4093daf2b63ebcf9e7e9"};
}
inline std::filesystem::path Path(bool mixed) {
    const auto* path=std::getenv(mixed ? "ROBO_DYNA_SOURCE_SECTION_MIXED_INVENTORY" : "ROBO_DYNA_SOURCE_ELASTIC_INVENTORY");
    output::Require(path&&*path,"Explicit layered source V3 fixture is required");return path;
}
inline SourceAssembly Load(bool mixed) { return SourceAssembly::Read(Path(mixed),Identity(mixed)); }
inline std::string Alter(const std::function<void(output::Document&)>& edit) {
    const auto bytes=output::ReadBounded(Path(false),Identity(false).bytes);output::Document d;
    d.Parse<rapidjson::kParseFullPrecisionFlag>(bytes.data(),bytes.size());
    output::Require(!d.HasParseError(),"Bad elastic source fixture");edit(d);
    rapidjson::StringBuffer buffer;rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
    output::Require(d.Accept(writer),"Invalid layered corruption fixture");
    return {buffer.GetString(),buffer.GetSize()};
}
} // namespace crash::modelio::assembly::test::section
