find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(l1_source "${CMAKE_CURRENT_SOURCE_DIR}/native")
execute_process(COMMAND "${Python3_EXECUTABLE}" -B "${l1_source}/verify_sources.py"
  RESULT_VARIABLE l1_status ERROR_VARIABLE l1_error)
if(NOT l1_status EQUAL 0)
  message(FATAL_ERROR "LAW1 force context verification failed: ${l1_error}")
endif()
add_custom_target(layered_law1_force_verify_sources COMMAND "${Python3_EXECUTABLE}" -B "${l1_source}/verify_sources.py" VERBATIM)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${l1_source}/verify_sources.py" "${l1_source}/source-manifest.json")
set(l1_modules "${CMAKE_CURRENT_BINARY_DIR}/law1-force-modules")
file(MAKE_DIRECTORY "${l1_modules}")
add_library(layered_law1_native_work STATIC "${l1_source}/NativeLaw1SectionWork.F90")
add_dependencies(layered_law1_native_work layered_native_verify_sources layered_law1_force_verify_sources)
get_target_property(l1_shared_includes layered_native_section INCLUDE_DIRECTORIES)
get_target_property(l1_point_modules law1_point_native Fortran_MODULE_DIRECTORY)
target_include_directories(layered_law1_native_work PRIVATE ${l1_shared_includes} "${l1_point_modules}")
set_target_properties(layered_law1_native_work PROPERTIES Fortran_MODULE_DIRECTORY "${l1_modules}")
target_compile_options(layered_law1_native_work PRIVATE -cpp -ffree-line-length-none -fcheck=bounds -fbacktrace -fno-fast-math -ffp-contract=off)
target_link_libraries(layered_law1_native_work PUBLIC law1_point_native)
function(l1_family target native)
  add_library(${target} STATIC ${ARGN})
  foreach(property INCLUDE_DIRECTORIES COMPILE_DEFINITIONS COMPILE_OPTIONS)
    get_target_property(value ${native} ${property})
    set_property(TARGET ${target} PROPERTY ${property} "${value}")
  endforeach()
  get_target_property(native_modules ${native} Fortran_MODULE_DIRECTORY)
  target_include_directories(${target} PRIVATE "${native_modules}" "${l1_modules}")
  set_target_properties(${target} PROPERTIES Fortran_MODULE_DIRECTORY "${l1_modules}")
  target_link_libraries(${target} PUBLIC ${native} layered_law1_native_work)
endfunction()
l1_family(layered_law1_native_qeph qeph_q1_native "${l1_source}/NativeLaw1QephSection.F" "${l1_source}/NativeLaw1QephForce.F")
l1_family(layered_law1_native_t3 t3_r3_native "${l1_source}/NativeLaw1T3Section.F" "${l1_source}/NativeLaw1T3Force.F")
add_library(shell_layered_law1_native_reference STATIC "${l1_source}/NativeLaw1Qeph.cpp" "${l1_source}/NativeLaw1T3.cpp")
target_include_directories(shell_layered_law1_native_reference PUBLIC "${TL_ROOT}" "${l1_source}")
target_compile_features(shell_layered_law1_native_reference PUBLIC cxx_std_17)
target_compile_options(shell_layered_law1_native_reference PRIVATE -fno-fast-math -ffp-contract=off)
target_link_libraries(shell_layered_law1_native_reference PUBLIC layered_law1_native_qeph layered_law1_native_t3 shell_layered_native_reference)
