enable_language(Fortran)
# Each existing native owner is constructed once. Centered parity uses the
# old complete family entrypoints alongside the new explicitly placed packets.
set(TL_SHELL_PLACEMENT_NATIVE ON CACHE BOOL "" FORCE)
set(TL_SHELL_PLACEMENT_CUDA OFF CACHE BOOL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../shell_reference_placement" placement-reference)
set(TL_TAB1_FORCE_NATIVE ON CACHE BOOL "" FORCE)
set(TL_TAB1_FORCE_CUDA OFF CACHE BOOL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../shell_tab1_force" centered-family)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(placed_source "${CMAKE_CURRENT_SOURCE_DIR}/native")
set(placed_prepared "${CMAKE_CURRENT_BINARY_DIR}/placed-force-prepared")
execute_process(COMMAND "${Python3_EXECUTABLE}" -B "${placed_source}/prepare_sources.py"
  --output "${placed_prepared}" RESULT_VARIABLE status ERROR_VARIABLE diagnostic)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Native placed family preparation failed: ${diagnostic}")
endif()
add_custom_target(shell_placement_force_sources
  COMMAND "${Python3_EXECUTABLE}" -B "${placed_source}/prepare_sources.py"
    --output "${placed_prepared}" --check VERBATIM)
get_target_property(placed_packet_modules shell_reference_placement_native Fortran_MODULE_DIRECTORY)
get_target_property(placed_glass_modules shell_tab1_glass_native Fortran_MODULE_DIRECTORY)
set(placed_caller_modules "${CMAKE_CURRENT_BINARY_DIR}/placed-caller-modules")
file(MAKE_DIRECTORY "${placed_caller_modules}")
add_library(shell_placement_force_native_caller STATIC native/NativeCaller.F90)
set_target_properties(shell_placement_force_native_caller PROPERTIES Fortran_MODULE_DIRECTORY "${placed_caller_modules}")
target_include_directories(shell_placement_force_native_caller PRIVATE "${placed_packet_modules}" "${placed_glass_modules}")
target_compile_options(shell_placement_force_native_caller PRIVATE -ffree-line-length-none -fcheck=bounds -fbacktrace -fno-fast-math -ffp-contract=off)
target_link_libraries(shell_placement_force_native_caller PUBLIC shell_reference_placement_native)
add_dependencies(shell_placement_force_native_caller shell_placement_force_sources)
function(placed_force_family target native)
  add_library(${target} STATIC ${ARGN})
  foreach(property INCLUDE_DIRECTORIES COMPILE_DEFINITIONS COMPILE_OPTIONS)
    get_target_property(value ${native} ${property})
    set_property(TARGET ${target} PROPERTY ${property} "${value}")
  endforeach()
  get_target_property(native_modules ${native} Fortran_MODULE_DIRECTORY)
  set(modules "${CMAKE_CURRENT_BINARY_DIR}/${target}-modules")
  file(MAKE_DIRECTORY "${modules}")
  set_target_properties(${target} PROPERTIES Fortran_MODULE_DIRECTORY "${modules}")
  target_include_directories(${target} PRIVATE "${native_modules}" "${placed_caller_modules}" "${modules}")
  target_link_libraries(${target} PUBLIC ${native} shell_placement_force_native_caller shell_layered_native_reference)
  add_dependencies(${target} shell_placement_force_sources)
endfunction()
placed_force_family(shell_placed_qeph_native qeph_q1_native
  "${placed_prepared}/PlacedQephMaterial.F" "${placed_prepared}/PlacedTab1QephSection.F" "${placed_prepared}/PlacedTab1QephForce.F")
placed_force_family(shell_placed_t3_native t3_r3_native
  "${placed_prepared}/PlacedT3Material.F" "${placed_prepared}/PlacedTab1T3Section.F" "${placed_prepared}/PlacedTab1T3Force.F")
add_library(shell_placement_force_test_support STATIC native/NativePacket.cpp)
target_include_directories(shell_placement_force_test_support PUBLIC "${TL_ROOT}")
target_compile_features(shell_placement_force_test_support PUBLIC cxx_std_17)
target_compile_options(shell_placement_force_test_support PRIVATE -fno-fast-math -ffp-contract=off)
target_link_libraries(shell_placement_force_test_support PUBLIC
  shell_placed_qeph_native shell_placed_t3_native shell_tab1_force_test_support GTest::gtest_main)
add_executable(shell_placement_force_native_check PlacementForceNativeTest.cpp)
target_compile_options(shell_placement_force_native_check PRIVATE -fno-fast-math -ffp-contract=off)
target_link_libraries(shell_placement_force_native_check PRIVATE shell_placement_force_test_support)
add_test(NAME shell_placement_force_native COMMAND shell_placement_force_native_check)
if(TL_PLACEMENT_FORCE_CUDA)
  enable_language(CUDA)
  find_package(CUDAToolkit REQUIRED)
  add_executable(shell_placement_force_cuda_check PlacementForceCudaTest.cu)
  target_link_libraries(shell_placement_force_cuda_check PRIVATE shell_placement_force_test_support CUDA::cudart)
  target_compile_features(shell_placement_force_cuda_check PRIVATE cxx_std_17 cuda_std_17)
  target_compile_options(shell_placement_force_cuda_check PRIVATE
    "$<$<COMPILE_LANGUAGE:CUDA>:--fmad=false;--prec-div=true;--prec-sqrt=true;--ftz=false;-Xcompiler=-fno-fast-math,-ffp-contract=off>")
  add_test(NAME shell_placement_force_cuda COMMAND shell_placement_force_cuda_check)
endif()
get_property(placed_tests DIRECTORY PROPERTY TESTS)
set_tests_properties(${placed_tests} PROPERTIES RUN_SERIAL TRUE PROCESSORS 1 TIMEOUT 120
  ENVIRONMENT "OMP_NUM_THREADS=1;OPENBLAS_NUM_THREADS=1;MKL_NUM_THREADS=1")
