get_filename_component(plasticity_binding_tl_root "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
include("${plasticity_binding_tl_root}/lib_src/elements/ShellBatchPlasticityBinding.cmake")
add_executable(shell_plasticity_binding_check "${CMAKE_CURRENT_LIST_DIR}/PlasticityBindingTest.cpp")
target_include_directories(shell_plasticity_binding_check PRIVATE "${plasticity_binding_tl_root}")
target_link_libraries(shell_plasticity_binding_check PRIVATE tl_shell_batch_plasticity_binding GTest::gtest_main)
target_compile_options(shell_plasticity_binding_check PRIVATE -fno-fast-math -ffp-contract=off)
add_test(NAME shell_plasticity_binding_check COMMAND shell_plasticity_binding_check)
set_tests_properties(shell_plasticity_binding_check PROPERTIES RUN_SERIAL TRUE PROCESSORS 1 TIMEOUT 30)
