load("@rules_cc//cc:defs.bzl", "cc_test")
cc_test(
    name = "host_check",
    srcs = ["HostTest.cpp"],
    deps = ["//lib_src/elements/solids:force_stiffness",
            "//lib_utest/qualification/solid18_force:test_values",
            "//lib_utest/qualification/solid24_force:test_values",
            "//lib_utest/qualification/solid6z_force:test_values",
            "@googletest//:gtest_main"],
    copts = ["-std=c++17", "-fno-fast-math", "-ffp-contract=off"],
)
