include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/Reader.cmake")
if(NOT TARGET robo_dyna_full_shell_source_mapping)
  add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../../output/full_shell" "${CMAKE_CURRENT_BINARY_DIR}/native_coordinate_source_io")
endif()
add_library(robo_dyna_source_native_coordinates STATIC "${CMAKE_CURRENT_LIST_DIR}/NativeCoordinates.cpp")
target_link_libraries(robo_dyna_source_native_coordinates PUBLIC robo_dyna_source_assembly robo_dyna_full_shell_source_mapping)
target_compile_features(robo_dyna_source_native_coordinates PUBLIC cxx_std_17)
target_compile_options(robo_dyna_source_native_coordinates PRIVATE -fno-fast-math -ffp-contract=off)
