include_guard(GLOBAL)
get_filename_component(robo_assembly_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(ROBO_DYNA_TL_ROOT "" CACHE PATH "TL-FEA source checkout supplying typed startup inputs")
if(NOT EXISTS "${ROBO_DYNA_TL_ROOT}/lib_src/elements/ShellBatchBinding.h" OR
   NOT EXISTS "${ROBO_DYNA_TL_ROOT}/lib_src/elements/ShellBatchPlasticityBinding.h")
  message(FATAL_ERROR "Assembly input adapters require an explicit TL-FEA source checkout with shell/material input declarations")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/Reader.cmake")
foreach(kind Shell Material)
  string(TOLOWER "${kind}" lower_kind)
  add_library(robo_dyna_source_assembly_${lower_kind}_input STATIC "${CMAKE_CURRENT_LIST_DIR}/SourceAssembly${kind}Input.cpp")
  target_link_libraries(robo_dyna_source_assembly_${lower_kind}_input PUBLIC robo_dyna_source_assembly)
  target_compile_options(robo_dyna_source_assembly_${lower_kind}_input PRIVATE -fno-fast-math -ffp-contract=off)
endforeach()
