"""Exact CMake-selected native Sensor Vulkan RT profile; no OptiX/Metal/CUDA TUs."""

SENSOR_GROUPS = {'management': {'cmake_group': 'Chrono_sensor',
                'sources': ['src/chrono_sensor/ChSensorManager.cpp', 'src/chrono_sensor/ChDynamicsManager.cpp'],
                'headers': ['src/chrono_sensor/ChApiSensor.h',
                            'src/chrono_sensor/ChSensorManager.h',
                            'src/chrono_sensor/ChDynamicsManager.h',
                            'src/chrono_sensor/ChFsiSphRender.h',
                            'src/chrono_sensor/ChSensorRenderTypes.h']},
 'sensors': {'cmake_group': 'Chrono_sensor_SENSORS',
             'sources': ['src/chrono_sensor/sensors/ChSensor.cpp',
                         'src/chrono_sensor/sensors/ChNoiseModel.cpp',
                         'src/chrono_sensor/sensors/ChIMUSensor.cpp',
                         'src/chrono_sensor/sensors/ChGPSSensor.cpp',
                         'src/chrono_sensor/sensors/ChTachometerSensor.cpp',
                         'src/chrono_sensor/sensors/Sensor.cpp',
                         'src/chrono_sensor/sensors/ChVulkanSensor.cpp',
                         'src/chrono_sensor/sensors/ChVulkanCameraSensor.cpp',
                         'src/chrono_sensor/sensors/ChCameraSensor.cpp',
                         'src/chrono_sensor/sensors/ChPhysCameraSensor.cpp',
                         'src/chrono_sensor/sensors/ChSegmentationCamera.cpp',
                         'src/chrono_sensor/sensors/ChDepthCamera.cpp',
                         'src/chrono_sensor/sensors/ChNormalCamera.cpp',
                         'src/chrono_sensor/sensors/ChLidarSensor.cpp',
                         'src/chrono_sensor/sensors/ChRadarSensor.cpp'],
             'headers': ['src/chrono_sensor/sensors/ChSensor.h',
                         'src/chrono_sensor/sensors/ChNoiseModel.h',
                         'src/chrono_sensor/sensors/ChIMUSensor.h',
                         'src/chrono_sensor/sensors/ChGPSSensor.h',
                         'src/chrono_sensor/sensors/ChTachometerSensor.h',
                         'src/chrono_sensor/sensors/ChSensorBuffer.h',
                         'src/chrono_sensor/sensors/Sensor.h',
                         'src/chrono_sensor/sensors/ChVulkanSensor.h',
                         'src/chrono_sensor/sensors/ChVulkanCameraSensor.h',
                         'src/chrono_sensor/sensors/ChCameraSensor.h',
                         'src/chrono_sensor/sensors/ChPhysCameraSensor.h',
                         'src/chrono_sensor/sensors/ChSegmentationCamera.h',
                         'src/chrono_sensor/sensors/ChDepthCamera.h',
                         'src/chrono_sensor/sensors/ChNormalCamera.h',
                         'src/chrono_sensor/sensors/ChLidarSensor.h',
                         'src/chrono_sensor/sensors/ChRadarSensor.h']},
 'filters': {'cmake_group': 'Chrono_sensor_FILTERS',
             'sources': ['src/chrono_sensor/filters/ChFilter.cpp',
                         'src/chrono_sensor/filters/ChFilterAccess.cpp',
                         'src/chrono_sensor/filters/ChFilterIMUUpdate.cpp',
                         'src/chrono_sensor/filters/ChFilterGPSUpdate.cpp',
                         'src/chrono_sensor/filters/ChFilterTachometerUpdate.cpp',
                         'src/chrono_sensor/filters/ChFilterCameraNoise.cpp',
                         'src/chrono_sensor/filters/ChFilterGrayscale.cpp',
                         'src/chrono_sensor/filters/ChFilterImageOps.cpp',
                         'src/chrono_sensor/filters/ChFilterVisualize.cpp',
                         'src/chrono_sensor/filters/ChFilterSave.cpp',
                         'src/chrono_sensor/filters/ChFilterLidarNoise.cpp',
                         'src/chrono_sensor/filters/ChFilterLidarIntensityClip.cpp',
                         'src/chrono_sensor/filters/ChFilterLidarReduce.cpp',
                         'src/chrono_sensor/filters/ChFilterPCfromDepth.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarProcess.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarXYZReturn.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarSavePC.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarXYZVisualize.cpp',
                         'src/chrono_sensor/filters/ChFilterRadarVisualizeCluster.cpp',
                         'src/chrono_sensor/filters/ChFilterSavePtCloud.cpp',
                         'src/chrono_sensor/filters/ChFilterVisualizePointCloud.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraDefocusBlur.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraVignetting.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraAggregator.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraNoise.cpp',
                         'src/chrono_sensor/filters/ChFilterPhysCameraExpsrToDV.cpp'],
             'headers': ['src/chrono_sensor/filters/ChFilter.h',
                         'src/chrono_sensor/filters/ChFilterAccess.h',
                         'src/chrono_sensor/filters/ChFilterIMUUpdate.h',
                         'src/chrono_sensor/filters/ChFilterGPSUpdate.h',
                         'src/chrono_sensor/filters/ChFilterTachometerUpdate.h',
                         'src/chrono_sensor/filters/ChFilterCameraNoise.h',
                         'src/chrono_sensor/filters/ChFilterGrayscale.h',
                         'src/chrono_sensor/filters/ChFilterImageOps.h',
                         'src/chrono_sensor/filters/ChFilterVisualize.h',
                         'src/chrono_sensor/filters/ChFilterSave.h',
                         'src/chrono_sensor/filters/ChFilterLidarNoise.h',
                         'src/chrono_sensor/filters/ChFilterLidarReduce.h',
                         'src/chrono_sensor/filters/ChFilterLidarIntensityClip.h',
                         'src/chrono_sensor/filters/ChFilterPCfromDepth.h',
                         'src/chrono_sensor/filters/ChFilterRadarProcess.h',
                         'src/chrono_sensor/filters/ChFilterRadarXYZReturn.h',
                         'src/chrono_sensor/filters/ChFilterRadarSavePC.h',
                         'src/chrono_sensor/filters/ChFilterRadarXYZVisualize.h',
                         'src/chrono_sensor/filters/ChFilterRadarVisualizeCluster.h',
                         'src/chrono_sensor/filters/ChFilterSavePtCloud.h',
                         'src/chrono_sensor/filters/ChFilterVisualizePointCloud.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraDefocusBlur.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraVignetting.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraAggregator.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraNoise.h',
                         'src/chrono_sensor/filters/ChFilterPhysCameraExpsrToDV.h']},
 'utilities': {'cmake_group': 'Chrono_sensor_UTILS',
               'sources': ['src/chrono_sensor/utils/ChSensorUtils.cpp',
                           'src/chrono_sensor/utils/ChSensorUtilsJSON.cpp',
                           'src/chrono_sensor/utils/ChGPSUtils.cpp',
                           'src/chrono_sensor/utils/Kdtree.cpp',
                           'src/chrono_sensor/utils/Dbscan.cpp'],
               'headers': ['src/chrono_sensor/utils/ChSensorUtils.h',
                           'src/chrono_sensor/utils/ChSensorUtilsJSON.h',
                           'src/chrono_sensor/utils/ChGPSUtils.h',
                           'src/chrono_sensor/utils/Kdtree.h',
                           'src/chrono_sensor/utils/Dbscan.h']},
 'vulkan': {'cmake_group': 'Chrono_sensor_VULKAN',
            'sources': ['src/chrono_sensor/vulkan/ChVulkanRTUtils.cpp',
                        'src/chrono_sensor/vulkan/ChVulkanRTDevice.cpp',
                        'src/chrono_sensor/vulkan/ChVulkanRTBuffer.cpp',
                        'src/chrono_sensor/vulkan/ChVulkanRTScene.cpp',
                        'src/chrono_sensor/vulkan/ChFilterVulkanRTRender.cpp',
                        'src/chrono_sensor/vulkan/ChVulkanRTEngine.cpp'],
            'headers': ['src/chrono_sensor/vulkan/ChVulkanRTDefinitions.h',
                        'src/chrono_sensor/vulkan/ChVulkanRTUtils.h',
                        'src/chrono_sensor/vulkan/ChVulkanRTDevice.h',
                        'src/chrono_sensor/vulkan/ChVulkanRTBuffer.h',
                        'src/chrono_sensor/vulkan/ChVulkanRTScene.h',
                        'src/chrono_sensor/vulkan/ChFilterVulkanRTRender.h',
                        'src/chrono_sensor/vulkan/ChVulkanRTEngine.h']}}

SENSOR_PRIVATE_HEADERS = ['src/chrono_sensor/filters/ChFilterVisualizeGuards.h',
 'src/chrono_sensor/utils/ChSensorImageCompare.h']

SENSOR_SHADERS = ['src/chrono_sensor/vulkan/shaders/chrono_sensor_vkrt.rgen',
 'src/chrono_sensor/vulkan/shaders/chrono_sensor_vkrt.rmiss',
 'src/chrono_sensor/vulkan/shaders/chrono_sensor_vkrt.rchit',
 'src/chrono_sensor/vulkan/shaders/chrono_sensor_vkrt_shadow.rmiss',
 'src/chrono_sensor/vulkan/shaders/chrono_sensor_vkrt_shadow.rahit']

SENSOR_CONFIG_TEMPLATE = "src/chrono_sensor/ChConfigSensor.h.in"
