enable_language(Fortran)
# Create each native owner once. Glass supplies the shared point/failure caller;
# the existing layered recurrence supplies complete family geometry and forces.
set(TL_TAB1_GLASS_NATIVE ON CACHE BOOL "" FORCE)
set(TL_TAB1_GLASS_CUDA OFF CACHE BOOL "" FORCE)
if(NOT TARGET shell_tab1_glass_native)
  add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../shell_tab1_glass" glass-section)
endif()
set(TL_SHELL_LAYERED_J2_ENABLE_CUDA OFF CACHE BOOL "" FORCE)
set(TL_SHELL_LAYERED_NATIVE_RECURRENCE ON CACHE BOOL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../shell_layered_j2" layered-reference)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(tab1_source "${CMAKE_CURRENT_SOURCE_DIR}/native")
set(tab1_prepared "${CMAKE_CURRENT_BINARY_DIR}/tab1-force-prepared")
execute_process(COMMAND "${Python3_EXECUTABLE}" -B "${tab1_source}/prepare_sources.py"
  --output "${tab1_prepared}" RESULT_VARIABLE tab1_status ERROR_VARIABLE tab1_diagnostic)
if(NOT tab1_status EQUAL 0)
  message(FATAL_ERROR "TAB1 force native source preparation failed: ${tab1_diagnostic}")
endif()
add_custom_target(shell_tab1_force_sources
  COMMAND "${Python3_EXECUTABLE}" -B "${tab1_source}/prepare_sources.py"
    --output "${tab1_prepared}" --check VERBATIM)
get_target_property(tab1_point_modules shell_tab1_glass_native Fortran_MODULE_DIRECTORY)
get_target_property(tab1_section_modules shell_layered_failure_native Fortran_MODULE_DIRECTORY)
get_target_property(tab1_layered_modules layered_native_qeph Fortran_MODULE_DIRECTORY)
set(tab1_caller_modules "${CMAKE_CURRENT_BINARY_DIR}/tab1-caller-modules")
file(MAKE_DIRECTORY "${tab1_caller_modules}")
add_library(shell_tab1_force_native_caller STATIC native/NativeCaller.F90)
set_target_properties(shell_tab1_force_native_caller PROPERTIES Fortran_MODULE_DIRECTORY "${tab1_caller_modules}")
target_include_directories(shell_tab1_force_native_caller PRIVATE "${tab1_point_modules}" "${tab1_section_modules}")
target_compile_options(shell_tab1_force_native_caller PRIVATE -ffree-line-length-none -fcheck=bounds -fbacktrace -fno-fast-math -ffp-contract=off)
target_link_libraries(shell_tab1_force_native_caller PUBLIC shell_tab1_glass_native)
add_dependencies(shell_tab1_force_native_caller shell_tab1_force_sources)

function(tab1_force_family target native)
  add_library(${target} STATIC ${ARGN})
  foreach(property INCLUDE_DIRECTORIES COMPILE_DEFINITIONS COMPILE_OPTIONS)
    get_target_property(value ${native} ${property})
    set_property(TARGET ${target} PROPERTY ${property} "${value}")
  endforeach()
  get_target_property(native_modules ${native} Fortran_MODULE_DIRECTORY)
  set(modules "${CMAKE_CURRENT_BINARY_DIR}/${target}-modules")
  file(MAKE_DIRECTORY "${modules}")
  set_target_properties(${target} PROPERTIES Fortran_MODULE_DIRECTORY "${modules}")
  target_include_directories(${target} PRIVATE "${native_modules}" "${tab1_caller_modules}" "${tab1_layered_modules}" "${modules}")
  target_link_libraries(${target} PUBLIC ${native} shell_tab1_force_native_caller shell_layered_native_reference)
  add_dependencies(${target} shell_tab1_force_sources)
endfunction()
tab1_force_family(shell_tab1_qeph_native qeph_q1_native
  "${tab1_prepared}/Tab1QephSection.F" "${tab1_prepared}/Tab1QephForce.F")
tab1_force_family(shell_tab1_t3_native t3_r3_native
  "${tab1_prepared}/Tab1T3Section.F" "${tab1_prepared}/Tab1T3Force.F")
add_library(shell_tab1_force_test_support STATIC native/NativePacket.cpp)
target_include_directories(shell_tab1_force_test_support PUBLIC "${TL_ROOT}")
target_compile_features(shell_tab1_force_test_support PUBLIC cxx_std_17)
target_compile_options(shell_tab1_force_test_support PRIVATE -fno-fast-math -ffp-contract=off)
target_link_libraries(shell_tab1_force_test_support PUBLIC
  shell_tab1_qeph_native shell_tab1_t3_native shell_tab1_glass_test_support GTest::gtest_main)
add_executable(shell_tab1_force_native_check Tab1ForceNativeTest.cpp)
target_compile_options(shell_tab1_force_native_check PRIVATE -fno-fast-math -ffp-contract=off)
target_link_libraries(shell_tab1_force_native_check PRIVATE shell_tab1_force_test_support)
add_test(NAME shell_tab1_force_native COMMAND shell_tab1_force_native_check)
set_tests_properties(shell_tab1_force_native PROPERTIES RUN_SERIAL TRUE PROCESSORS 1 TIMEOUT 60
  ENVIRONMENT "OMP_NUM_THREADS=1;OPENBLAS_NUM_THREADS=1;MKL_NUM_THREADS=1")
if(TL_TAB1_FORCE_CUDA)
  enable_language(CUDA)
  find_package(CUDAToolkit REQUIRED)
  add_executable(shell_tab1_force_cuda_check Tab1ForceCudaTest.cu)
  target_link_libraries(shell_tab1_force_cuda_check PRIVATE shell_tab1_force_test_support CUDA::cudart)
  target_compile_features(shell_tab1_force_cuda_check PRIVATE cxx_std_17 cuda_std_17)
  target_compile_options(shell_tab1_force_cuda_check PRIVATE
    "$<$<COMPILE_LANGUAGE:CUDA>:--fmad=false;--prec-div=true;--prec-sqrt=true;--ftz=false;-Xcompiler=-fno-fast-math,-ffp-contract=off>")
  add_test(NAME shell_tab1_force_cuda COMMAND shell_tab1_force_cuda_check)
  set_tests_properties(shell_tab1_force_cuda PROPERTIES RUN_SERIAL TRUE PROCESSORS 1 TIMEOUT 120
    ENVIRONMENT "OMP_NUM_THREADS=1;OPENBLAS_NUM_THREADS=1;MKL_NUM_THREADS=1")
endif()
