if(NOT TARGET tl_shell_batch_failure_binding)
  include("${CMAKE_CURRENT_LIST_DIR}/ShellBatchPlasticityBinding.cmake")
  add_library(tl_shell_batch_failure_binding STATIC "${CMAKE_CURRENT_LIST_DIR}/failure/ShellFailureBinding.cpp")
  target_link_libraries(tl_shell_batch_failure_binding PUBLIC tl_shell_batch_plasticity_binding)
  target_compile_features(tl_shell_batch_failure_binding PUBLIC cxx_std_17)
  target_compile_options(tl_shell_batch_failure_binding PRIVATE -fno-fast-math -ffp-contract=off)
endif()
