"""Retained yaml-cpp0.8 source owners and the original core YAML adapter."""

YAML_SOURCES = [
    "src/chrono_thirdparty/yaml-cpp/src/binary.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/contrib/graphbuilder.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/contrib/graphbuilderadapter.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/convert.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/depthguard.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/directives.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/emit.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/emitfromevents.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/emitter.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/emitterstate.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/emitterutils.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/exceptions.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/exp.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/fptostring.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/memory.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/node.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/node_data.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/nodebuilder.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/nodeevents.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/null.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/ostream_wrapper.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/parse.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/parser.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/regex_yaml.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/scanner.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/scanscalar.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/scantag.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/scantoken.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/simplekey.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/singledocparser.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/stream.cpp",
    "src/chrono_thirdparty/yaml-cpp/src/tag.cpp"
]

YAML_PRIVATE_HEADERS = [
    "src/chrono_thirdparty/yaml-cpp/src/collectionstack.h",
    "src/chrono_thirdparty/yaml-cpp/src/contrib/dragonbox.h",
    "src/chrono_thirdparty/yaml-cpp/src/contrib/graphbuilderadapter.h",
    "src/chrono_thirdparty/yaml-cpp/src/directives.h",
    "src/chrono_thirdparty/yaml-cpp/src/emitterstate.h",
    "src/chrono_thirdparty/yaml-cpp/src/emitterutils.h",
    "src/chrono_thirdparty/yaml-cpp/src/exp.h",
    "src/chrono_thirdparty/yaml-cpp/src/indentation.h",
    "src/chrono_thirdparty/yaml-cpp/src/nodebuilder.h",
    "src/chrono_thirdparty/yaml-cpp/src/nodeevents.h",
    "src/chrono_thirdparty/yaml-cpp/src/ptr_vector.h",
    "src/chrono_thirdparty/yaml-cpp/src/regex_yaml.h",
    "src/chrono_thirdparty/yaml-cpp/src/regeximpl.h",
    "src/chrono_thirdparty/yaml-cpp/src/scanner.h",
    "src/chrono_thirdparty/yaml-cpp/src/scanscalar.h",
    "src/chrono_thirdparty/yaml-cpp/src/scantag.h",
    "src/chrono_thirdparty/yaml-cpp/src/setting.h",
    "src/chrono_thirdparty/yaml-cpp/src/singledocparser.h",
    "src/chrono_thirdparty/yaml-cpp/src/stream.h",
    "src/chrono_thirdparty/yaml-cpp/src/streamcharsource.h",
    "src/chrono_thirdparty/yaml-cpp/src/stringsource.h",
    "src/chrono_thirdparty/yaml-cpp/src/tag.h",
    "src/chrono_thirdparty/yaml-cpp/src/token.h"
]

YAML_PUBLIC_HEADERS = [
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/anchor.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/binary.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/contrib/anchordict.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/contrib/graphbuilder.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/depthguard.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/dll.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/emitfromevents.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/emitter.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/emitterdef.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/emittermanip.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/emitterstyle.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/eventhandler.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/exceptions.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/fptostring.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/mark.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/convert.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/detail/impl.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/detail/iterator.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/detail/iterator_fwd.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/detail/memory.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/detail/node.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/detail/node_data.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/detail/node_iterator.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/detail/node_ref.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/emit.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/impl.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/iterator.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/node.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/parse.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/ptr.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/node/type.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/noexcept.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/null.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/ostream_wrapper.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/parser.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/stlemitter.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/traits.h",
    "src/chrono_thirdparty/yaml-cpp/include/yaml-cpp/yaml.h"
]

YAML_EVIDENCE = [
    "src/chrono_thirdparty/yaml-cpp/CMakeLists.txt",
    "src/chrono_thirdparty/yaml-cpp/LICENSE",
    "src/chrono/input_output/ChUtilsYAML.cpp",
    "src/chrono/input_output/ChUtilsYAML.h"
]

YAML_SOURCE_EXPORTS = [path for path in YAML_EVIDENCE if not path.startswith("src/chrono_thirdparty/yaml-cpp/")]
