include_guard(GLOBAL)
if(NOT TARGET robo_dyna_physical_run_records)
  include("${CMAKE_CURRENT_LIST_DIR}/../../../../output/physical_run/PhysicalRun.cmake")
endif()
add_library(robo_dyna_two_interval_replay_support STATIC "${CMAKE_CURRENT_LIST_DIR}/TwoIntervalReplay.cpp")
target_link_libraries(robo_dyna_two_interval_replay_support PUBLIC robo_dyna_physical_run_records GTest::gtest)
target_compile_features(robo_dyna_two_interval_replay_support PUBLIC cxx_std_17)
target_compile_options(robo_dyna_two_interval_replay_support PRIVATE -fno-fast-math -ffp-contract=off)
add_executable(robo_dyna_retained_two_interval_check "${CMAKE_CURRENT_LIST_DIR}/RetainedArchiveTest.cpp")
target_link_libraries(robo_dyna_retained_two_interval_check PRIVATE robo_dyna_two_interval_replay_support GTest::gtest_main)
target_compile_options(robo_dyna_retained_two_interval_check PRIVATE -fno-fast-math -ffp-contract=off)
add_test(NAME vehicle_run_retained_two_intervals COMMAND robo_dyna_retained_two_interval_check)
set_tests_properties(vehicle_run_retained_two_intervals PROPERTIES
  TIMEOUT 360 RUN_SERIAL TRUE PROCESSORS 2 LABELS "host;retained-archive;two-interval-readback")
