load("@rules_cuda//cuda:defs.bzl", "cuda_library")
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nodal_rigid_group",
    srcs = ["NodalRigidGroupModel.cpp"],
    hdrs = ["NodalRigidGroupModel.h", "NodalRigidGroupMath.h"],
    copts = ["-std=c++17", "-fno-fast-math", "-ffp-contract=off"],
    deps = ["//lib_src/math:fixed3", "//lib_src/math:quaternion", "@eigen//:eigen"],
)

cuda_library(
    name = "FEAT10ConstraintManager",
    srcs = [
        "FEAT10ConstraintManager.cu",
        "FEAT10ConstraintJoints.cu",
        "FEAT10ConstraintPrimitives.cu",
    ],
    hdrs = ["FEAT10ConstraintManager.h"],
    copts = ["--std=c++17", "-O3", "--use_fast_math", "--extra-device-vectorization"],
    linkopts = ["-lcudart"],
    deps = [
        "//lib_src/elements:FEAT10Data",
        "//lib_utils:cuda_utils",
        "@eigen//:eigen",
    ],
)
